"""Cardiovascular system diagnoses (ICD-10 chapter IX)."""

CARDIOLOGY_DIAGNOSES: list[dict] = [
    {
        "id": "card_001", "name": "Myocardial Infarction", "icd10": "I21",
        "symptoms": "chest pain, crushing chest pain, left arm pain, jaw pain, shortness of breath, sweating, nausea, vomiting, dizziness, palpitations, sense of doom",
        "specialties": "Cardiology, Emergency Medicine",
        "prevalence": "common", "risk_factors": "smoking, hypertension, diabetes, high cholesterol, obesity, family history, sedentary lifestyle, male sex",
        "demographics": "males over 45, females over 55, post-menopausal women",
        "red_flags": "severe crushing chest pain, sudden onset, radiation to arm/jaw, diaphoresis, hemodynamic instability, syncope",
        "urgency": "emergency",
        "description": "Heart attack caused by acute occlusion of a coronary artery leading to myocardial necrosis. Presents with crushing chest pain radiating to left arm and jaw, diaphoresis, and dyspnea.",
    },
    {
        "id": "card_002", "name": "Unstable Angina", "icd10": "I20.0",
        "symptoms": "chest pain, angina at rest, chest pressure, shortness of breath, new onset angina, worsening angina, angina not relieved by rest or nitroglycerin",
        "specialties": "Cardiology, Emergency Medicine",
        "prevalence": "common", "risk_factors": "smoking, hypertension, diabetes, high cholesterol, coronary artery disease history",
        "demographics": "males over 40, females over 50",
        "red_flags": "chest pain at rest, angina unresponsive to nitroglycerin, new onset angina, crescendo pattern",
        "urgency": "emergency",
        "description": "Acute coronary syndrome without myocardial necrosis. Chest pain occurs at rest or with minimal exertion, representing unstable plaque in coronary arteries.",
    },
    {
        "id": "card_003", "name": "Stable Angina", "icd10": "I20.8",
        "symptoms": "chest pain with exertion, chest pressure, substernal pain, pain relieved by rest, pain relieved by nitroglycerin, shortness of breath on exertion",
        "specialties": "Cardiology",
        "prevalence": "common", "risk_factors": "smoking, hypertension, diabetes, high cholesterol, family history, male sex",
        "demographics": "middle-aged and older adults",
        "red_flags": "change in angina pattern, angina at rest (suggests progression to unstable angina)",
        "urgency": "urgent",
        "description": "Predictable chest pain triggered by exertion and relieved by rest or nitroglycerin. Caused by fixed coronary artery narrowing.",
    },
    {
        "id": "card_004", "name": "Atrial Fibrillation", "icd10": "I48",
        "symptoms": "palpitations, irregular heartbeat, shortness of breath, dizziness, fatigue, chest discomfort, exercise intolerance, lightheadedness",
        "specialties": "Cardiology, Electrophysiology",
        "prevalence": "common", "risk_factors": "hypertension, heart failure, valvular disease, obesity, sleep apnea, alcohol, hyperthyroidism",
        "demographics": "increases with age, more common in males",
        "red_flags": "rapid ventricular response, hemodynamic instability, chest pain, syncope, acute heart failure",
        "urgency": "urgent",
        "description": "Irregularly irregular cardiac rhythm due to disorganized atrial electrical activity. Increases stroke risk five-fold.",
    },
    {
        "id": "card_005", "name": "Heart Failure (HFrEF)", "icd10": "I50.1",
        "symptoms": "shortness of breath, orthopnea, paroxysmal nocturnal dyspnea, peripheral edema, fatigue, exercise intolerance, weight gain, jugular venous distension, crackles on auscultation",
        "specialties": "Cardiology, Internal Medicine",
        "prevalence": "common", "risk_factors": "coronary artery disease, hypertension, diabetes, cardiomyopathy, valvular disease, obesity",
        "demographics": "older adults over 60, higher in males",
        "red_flags": "acute pulmonary edema, cardiogenic shock, respiratory distress, hypotension",
        "urgency": "emergency",
        "description": "The heart cannot pump enough blood to meet metabolic demands. Characterized by reduced ejection fraction (HFrEF, EF<40%) with congestion symptoms.",
    },
    {
        "id": "card_006", "name": "Heart Failure with Preserved EF (HFpEF)", "icd10": "I50.3",
        "symptoms": "shortness of breath on exertion, exercise intolerance, fatigue, peripheral edema, orthopnea, paroxysmal nocturnal dyspnea, diastolic dysfunction",
        "specialties": "Cardiology",
        "prevalence": "common", "risk_factors": "hypertension, diabetes, obesity, atrial fibrillation, aging, female sex",
        "demographics": "older adults, females over 65",
        "red_flags": "acute decompensation, pulmonary edema",
        "urgency": "urgent",
        "description": "Heart failure with preserved ejection fraction (EF>=50%). The heart muscle is stiff and cannot fill properly despite normal pumping function.",
    },
    {
        "id": "card_007", "name": "Hypertensive Crisis", "icd10": "I16",
        "symptoms": "severe headache, blurred vision, chest pain, shortness of breath, nosebleed, confusion, nausea, vomiting, seizures, blood pressure above 180/120",
        "specialties": "Emergency Medicine, Cardiology, Nephrology",
        "prevalence": "moderate", "risk_factors": "uncontrolled hypertension, medication non-compliance, renal disease, pheochromocytoma, drug use",
        "demographics": "adults with known hypertension, more common in African Americans",
        "red_flags": "hypertensive emergency with end-organ damage, encephalopathy, aortic dissection, pulmonary edema, eclampsia",
        "urgency": "emergency",
        "description": "Severely elevated blood pressure (>180/120 mmHg) with or without end-organ damage. Hypertensive emergency requires immediate blood pressure reduction.",
    },
    {
        "id": "card_008", "name": "Aortic Dissection", "icd10": "I71.0",
        "symptoms": "sudden severe chest pain, tearing chest pain radiating to back, back pain between shoulder blades, syncope, shortness of breath, stroke symptoms, pulse deficit, blood pressure differential between arms",
        "specialties": "Cardiology, Cardiothoracic Surgery, Emergency Medicine",
        "prevalence": "uncommon", "risk_factors": "hypertension, Marfan syndrome, Ehlers-Danlos, bicuspid aortic valve, aortic aneurysm, cocaine use, pregnancy",
        "demographics": "males 40-70, bimodal distribution",
        "red_flags": "sudden tearing chest/back pain, blood pressure differential between arms, pulse deficits, aortic regurgitation murmur, malperfusion syndromes",
        "urgency": "emergency",
        "description": "Tear in the aortic intima allowing blood to dissect through the media layer. A surgical emergency with high mortality if untreated.",
    },
    {
        "id": "card_009", "name": "Pulmonary Embolism", "icd10": "I26",
        "symptoms": "sudden shortness of breath, pleuritic chest pain, cough, hemoptysis, tachycardia, tachypnea, leg swelling, calf pain, syncope, anxiety, low oxygen saturation",
        "specialties": "Pulmonology, Emergency Medicine, Hematology",
        "prevalence": "common", "risk_factors": "immobility, surgery, cancer, oral contraceptives, pregnancy, obesity, DVT history, thrombophilia, long travel",
        "demographics": "adults 40-80, higher in females with risk factors",
        "red_flags": "massive PE with hypotension, cardiac arrest, right heart failure, syncope, respiratory failure",
        "urgency": "emergency",
        "description": "Blood clot in pulmonary vasculature, usually from deep vein thrombosis. Can range from subsegmental to massive with hemodynamic collapse.",
    },
    {
        "id": "card_010", "name": "Deep Vein Thrombosis", "icd10": "I82.4",
        "symptoms": "leg swelling, calf pain, warmth, redness, tenderness, palpable cord, superficial venous dilation, skin discoloration",
        "specialties": "Vascular Surgery, Hematology, Internal Medicine",
        "prevalence": "common", "risk_factors": "immobility, surgery, cancer, oral contraceptives, pregnancy, obesity, DVT history, thrombophilia",
        "demographics": "adults over 40, higher with immobilization",
        "red_flags": "phlegmasia cerulea dolens (blue leg), phlegmasia alba dolens (white leg), venous gangrene, signs of PE",
        "urgency": "urgent",
        "description": "Blood clot in deep veins, typically of the lower extremity. Major concern is embolization to lungs causing pulmonary embolism.",
    },
    {
        "id": "card_011", "name": "Pericarditis", "icd10": "I30",
        "symptoms": "sharp chest pain, pleuritic chest pain worse when lying flat, pain relieved by sitting forward, pericardial friction rub, fever, malaise, shortness of breath",
        "specialties": "Cardiology",
        "prevalence": "moderate", "risk_factors": "viral infection, autoimmune disease, uremia, malignancy, post-MI (Dressler syndrome), tuberculosis",
        "demographics": "young males 20-50, any age with autoimmune conditions",
        "red_flags": "cardiac tamponade (hypotension, muffled heart sounds, JVD), purulent pericarditis, hemodynamic instability",
        "urgency": "urgent",
        "description": "Inflammation of the pericardium causing sharp chest pain that improves leaning forward. Can lead to pericardial effusion and cardiac tamponade.",
    },
    {
        "id": "card_012", "name": "Cardiac Tamponade", "icd10": "I31.9",
        "symptoms": "hypotension, tachycardia, jugular venous distension, muffled heart sounds, pulsus paradoxus, shortness of breath, anxiety, chest discomfort, cyanosis",
        "specialties": "Emergency Medicine, Cardiology, Cardiothoracic Surgery",
        "prevalence": "uncommon", "risk_factors": "pericarditis, malignancy, trauma, uremia, aortic dissection, post-surgery",
        "demographics": "any age depending on cause",
        "red_flags": "Beck triad (hypotension, JVD, muffled heart sounds), electromechanical dissociation, PEA arrest",
        "urgency": "emergency",
        "description": "Life-threatening accumulation of fluid in the pericardial space compressing the heart. Requires emergent pericardiocentesis.",
    },
    {
        "id": "card_013", "name": "Myocarditis", "icd10": "I40",
        "symptoms": "chest pain, shortness of breath, fatigue, fever, palpitations, heart failure symptoms, myalgias, arrhythmias, flu-like symptoms",
        "specialties": "Cardiology, Internal Medicine",
        "prevalence": "uncommon", "risk_factors": "viral infection (Coxsackievirus, adenovirus, parvovirus B19), autoimmune disease, drug reaction, COVID-19",
        "demographics": "young adults 20-40, higher in males",
        "red_flags": "fulminant myocarditis with cardiogenic shock, severe arrhythmias, sudden cardiac death",
        "urgency": "emergency",
        "description": "Inflammation of the heart muscle, usually viral. Can range from mild chest pain to fulminant heart failure requiring mechanical support.",
    },
    {
        "id": "card_014", "name": "Dilated Cardiomyopathy", "icd10": "I42.0",
        "symptoms": "shortness of breath, fatigue, exercise intolerance, peripheral edema, weight gain, palpitations, orthopnea, paroxysmal nocturnal dyspnea",
        "specialties": "Cardiology",
        "prevalence": "moderate", "risk_factors": "alcohol abuse, viral infection, family history, pregnancy (peripartum), chemotherapy (doxorubicin), thyroid disease",
        "demographics": "males 20-60, African Americans at higher risk",
        "red_flags": "decompensated heart failure, severe arrhythmias, thromboembolism, sudden cardiac death",
        "urgency": "urgent",
        "description": "Enlarged and weakened heart chambers with reduced contractility. Leading cause of heart failure in younger patients.",
    },
    {
        "id": "card_015", "name": "Hypertrophic Cardiomyopathy", "icd10": "I42.1",
        "symptoms": "shortness of breath, chest pain with exertion, syncope, palpitations, exercise intolerance, heart murmur (dynamic), sudden cardiac death in young athletes",
        "specialties": "Cardiology, Electrophysiology",
        "prevalence": "moderate (1:500)", "risk_factors": "genetic (sarcomere mutations), family history of sudden cardiac death, athletic training",
        "demographics": "any age, diagnosed in young adults, leading cause of sudden cardiac death in young athletes",
        "red_flags": "sudden cardiac death, syncope during exercise, ventricular tachycardia, family history of sudden death",
        "urgency": "urgent",
        "description": "Genetic condition causing asymmetric thickening of the heart muscle, particularly the septum. Can cause dynamic left ventricular outflow obstruction.",
    },
    {
        "id": "card_016", "name": "Infective Endocarditis", "icd10": "I33",
        "symptoms": "fever, chills, night sweats, new heart murmur, splinter hemorrhages, Janeway lesions, Osler nodes, Roth spots, splenomegaly, fatigue, weight loss, embolic phenomena",
        "specialties": "Cardiology, Infectious Disease",
        "prevalence": "uncommon", "risk_factors": "prosthetic valve, IV drug use, dental procedures, rheumatic heart disease, immunosuppression, poor dental hygiene",
        "demographics": "IV drug users (tricuspid valve), elderly with valvular disease",
        "red_flags": "heart failure from valvular destruction, septic emboli, mycotic aneurysm, splenic abscess, vertebral osteomyelitis",
        "urgency": "emergency",
        "description": "Infection of heart valves or endocardial surface, usually bacterial. Can cause valvular destruction, embolic events, and systemic sepsis.",
    },
    {
        "id": "card_017", "name": "Mitral Valve Prolapse", "icd10": "I34.1",
        "symptoms": "chest pain (non-exertional), palpitations, anxiety, fatigue, shortness of breath, mid-systolic click on auscultation, mitral regurgitation",
        "specialties": "Cardiology",
        "prevalence": "common", "risk_factors": "connective tissue disorders (Marfan, Ehlers-Danlos), female sex, family history",
        "demographics": "young to middle-aged adults, females more than males",
        "red_flags": "progressive mitral regurgitation, heart failure, infective endocarditis risk",
        "urgency": "routine",
        "description": "Billowing of one or both mitral valve leaflets into the left atrium during systole. Usually benign but can cause significant regurgitation.",
    },
    {
        "id": "card_018", "name": "Aortic Stenosis", "icd10": "I35.0",
        "symptoms": "shortness of breath on exertion, syncope with exertion, angina, heart failure, reduced exercise tolerance, slow-rising pulse, systolic murmur",
        "specialties": "Cardiology, Cardiothoracic Surgery",
        "prevalence": "common in elderly", "risk_factors": "calcific (aging), bicuspid aortic valve, rheumatic heart disease",
        "demographics": "elderly over 70, congenital bicuspid valve patients 50-60",
        "red_flags": "syncope, angina, heart failure (classic triad), sudden cardiac death",
        "urgency": "urgent",
        "description": "Narrowing of the aortic valve opening, most commonly from calcific disease in elderly. Severe AS has a 50% mortality at 2 years if untreated.",
    },
    {
        "id": "card_019", "name": "Peripheral Arterial Disease", "icd10": "I73.9",
        "symptoms": "leg pain with walking (claudication), leg cramping, cold extremity, pale skin, hair loss on legs, slow wound healing, absent pulses, shiny skin",
        "specialties": "Vascular Surgery, Cardiology",
        "prevalence": "common", "risk_factors": "smoking, diabetes, hypertension, high cholesterol, age over 50",
        "demographics": "adults over 50, males more than females, diabetes patients",
        "red_flags": "critical limb ischemia, rest pain, tissue necrosis, gangrene, acute limb ischemia",
        "urgency": "urgent",
        "description": "Narrowing of peripheral arteries, most commonly in the legs, due to atherosclerosis. Marker of systemic cardiovascular disease.",
    },
    {
        "id": "card_020", "name": "Ventricular Tachycardia", "icd10": "I47.2",
        "symptoms": "palpitations, dizziness, lightheadedness, syncope, chest pain, shortness of breath, cardiac arrest, near-syncope",
        "specialties": "Cardiology, Electrophysiology, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "coronary artery disease, prior MI, cardiomyopathy, electrolyte abnormalities, long QT syndrome, Brugada syndrome",
        "demographics": "adults with structural heart disease",
        "red_flags": "hemodynamically unstable VT, pulseless VT (cardiac arrest), sustained VT, polymorphic VT (Torsades de Pointes)",
        "urgency": "emergency",
        "description": "Fast heart rhythm originating from the ventricles (>100 bpm). Can be life-threatening, especially in the setting of structural heart disease.",
    },
    {
        "id": "card_021", "name": "Bradyarrhythmia", "icd10": "I49.5",
        "symptoms": "fatigue, dizziness, lightheadedness, syncope, shortness of breath, exercise intolerance, slow heart rate, bradycardia",
        "specialties": "Cardiology, Electrophysiology",
        "prevalence": "moderate", "risk_factors": "aging, medication use (beta-blockers, calcium channel blockers, digoxin), sick sinus syndrome, heart block",
        "demographics": "elderly over 65, athletes",
        "red_flags": "high-grade AV block, complete heart block, asystole, hemodynamic instability, Adams-Stokes attacks",
        "urgency": "urgent",
        "description": "Abnormally slow heart rhythms including sinus bradycardia, AV block, and sick sinus syndrome. May require pacemaker implantation.",
    },
    {
        "id": "card_022", "name": "Supraventricular Tachycardia", "icd10": "I47.1",
        "symptoms": "sudden onset rapid heartbeat, palpitations, dizziness, shortness of breath, chest discomfort, anxiety, polyuria (after episode), syncope",
        "specialties": "Cardiology, Electrophysiology",
        "prevalence": "common", "risk_factors": "accessory pathway (WPW), AV nodal reentry, caffeine, alcohol, stress, pregnancy",
        "demographics": "young to middle-aged adults, females more than males",
        "red_flags": "pre-excited atrial fibrillation (WPW), hemodynamic instability, heart failure",
        "urgency": "urgent",
        "description": "Rapid heart rhythm originating above the ventricles, typically 150-250 bpm. Often paroxysmal with sudden onset and termination.",
    },
    {
        "id": "card_023", "name": "Cardiogenic Shock", "icd10": "R57.0",
        "symptoms": "hypotension, tachycardia, cool extremities, confusion, oliguria, shortness of breath, pulmonary edema, altered mental status, diaphoresis",
        "specialties": "Emergency Medicine, Cardiology, Critical Care",
        "prevalence": "uncommon", "risk_factors": "massive MI, acute mitral regurgitation, ventricular septal rupture, fulminant myocarditis, end-stage cardiomyopathy",
        "demographics": "adults with severe cardiac disease",
        "red_flags": "systolic BP <90 mmHg, cardiac index <1.8, pulmonary capillary wedge pressure >18, multi-organ failure",
        "urgency": "emergency",
        "description": "Severe heart failure where the heart cannot maintain adequate cardiac output, causing tissue hypoperfusion. Mortality 50-80% without intervention.",
    },
    {
        "id": "card_024", "name": "Long QT Syndrome", "icd10": "I45.8",
        "symptoms": "palpitations, syncope, seizures, sudden cardiac arrest, dizziness, sudden death (especially during exercise or emotional stress)",
        "specialties": "Cardiology, Electrophysiology, Genetics",
        "prevalence": "uncommon", "risk_factors": "genetic (congenital), medications that prolong QT, electrolyte abnormalities (hypokalemia, hypomagnesemia)",
        "demographics": "young people, diagnosed in childhood/adolescence",
        "red_flags": "Torsades de Pointes, cardiac arrest, sudden unexplained death in young family members",
        "urgency": "emergency",
        "description": "Inherited or acquired condition with prolonged cardiac repolarization, predisposing to dangerous ventricular arrhythmias.",
    },
    {
        "id": "card_025", "name": "Cardiac Arrest", "icd10": "I46",
        "symptoms": "sudden loss of consciousness, no pulse, no breathing, unresponsive, collapse, agonal breathing",
        "specialties": "Emergency Medicine, Cardiology, Critical Care",
        "prevalence": "common", "risk_factors": "coronary artery disease, prior MI, cardiomyopathy, arrhythmia, electrocution, drowning, drug overdose",
        "demographics": "adults, increases with age",
        "red_flags": "witnessed collapse, bystander CPR availability, shockable vs non-shockable rhythm",
        "urgency": "emergency",
        "description": "Sudden cessation of effective cardiac function. Without immediate CPR and defibrillation, death occurs within minutes. VF/VT is the most common initial rhythm.",
    },
]
