"""Emergency and toxicology diagnoses (ICD-10 chapters XVIII-XX)."""

EMERGENCY_DIAGNOSES: list[dict] = [
    {
        "id": "emer_001", "name": "Anaphylaxis", "icd10": "T78.2",
        "symptoms": "urticaria, angioedema, wheezing, stridor, shortness of breath, hypotension, tachycardia, dizziness, GI symptoms (nausea, vomiting, diarrhea), throat tightening",
        "specialties": "Emergency Medicine, Allergy/Immunology",
        "prevalence": "common", "risk_factors": "food allergies (nuts, shellfish), medications (penicillin, NSAIDs), insect stings, latex, exercise-induced",
        "demographics": "all ages, higher in atopic individuals, can occur at any time even without prior allergy history",
        "red_flags": "airway compromise, cardiovascular collapse, biphasic reaction, death within minutes",
        "urgency": "emergency",
        "description": "Severe systemic allergic reaction with rapid onset. Treatment: immediate IM epinephrine (anterolateral thigh), IV fluids, antihistamines, corticosteroids.",
    },
    {
        "id": "emer_002", "name": "Acute Asthma (Status Asthmaticus)", "icd10": "J46",
        "symptoms": "severe wheezing, inability to speak in sentences, SpO2 <90%, silent chest, accessory muscle use, cyanosis, exhaustion, peak flow <25% predicted",
        "specialties": "Emergency Medicine, Pulmonology",
        "prevalence": "common", "risk_factors": "severe asthma, non-compliance, respiratory infection, allergen exposure, NSAID/aspirin sensitivity",
        "demographics": "asthmatics of any age",
        "red_flags": "silent chest (ominous), cyanosis, altered consciousness, respiratory arrest",
        "urgency": "emergency",
        "description": "Life-threatening asthma exacerbation unresponsive to initial bronchodilator therapy. Requires aggressive treatment including IV magnesium, epinephrine, and intubation.",
    },
    {
        "id": "emer_003", "name": "Acute Myocardial Infarction (STEMI)", "icd10": "I21",
        "symptoms": "crushing chest pain, diaphoresis, shortness of breath, nausea, arm/jaw radiation, sense of doom, syncope",
        "specialties": "Emergency Medicine, Cardiology, Interventional Cardiology",
        "prevalence": "common", "risk_factors": "smoking, hypertension, diabetes, hyperlipidemia, family history, obesity",
        "demographics": "males >45, females >55, risk increases with age",
        "red_flags": "cardiogenic shock, VT/VF, heart failure, mechanical complications (papillary muscle rupture, VSD)",
        "urgency": "emergency",
        "description": "STEMI is a medical emergency requiring door-to-balloon time <90 minutes. ECG shows ST elevation. Treatment: emergent PCI or thrombolysis.",
    },
    {
        "id": "emer_004", "name": "Acute Stroke (Ischemic)", "icd10": "I63",
        "symptoms": "sudden facial droop, arm weakness, speech difficulty (FAST), vision loss, ataxia, vertigo, headache, altered consciousness",
        "specialties": "Emergency Medicine, Neurology, Interventional Neuroradiology",
        "prevalence": "common", "risk_factors": "atrial fibrillation, hypertension, diabetes, carotid disease, prior TIA, smoking",
        "demographics": "adults >55, risk doubles each decade after 55",
        "red_flags": "large vessel occlusion ( NIHSS >6), intracranial hemorrhage (CT needed first), malignant edema",
        "urgency": "emergency",
        "description": "Time-critical emergency. Door-to-CT <25 min, door-to-needle (tPA) <60 min, door-to-groin (thrombectomy) <90 min. 'Time is brain'.",
    },
    {
        "id": "emer_005", "name": "Diabetic Ketoacidosis (DKA)", "icd10": "E11.1",
        "symptoms": "polyuria, polydipsia, nausea, vomiting, abdominal pain, Kussmaul breathing, fruity breath, dehydration, altered consciousness",
        "specialties": "Emergency Medicine, Endocrinology",
        "prevalence": "common", "risk_factors": "Type 1 diabetes, insulin non-compliance, infection, new-onset diabetes, MI, pregnancy",
        "demographics": "Type 1 diabetics, can be initial presentation of diabetes",
        "red_flags": "cerebral edema (children), severe hypokalemia, ARDS, altered consciousness, pH <7.0",
        "urgency": "emergency",
        "description": "Metabolic emergency with hyperglycemia, ketosis, and acidosis. Treatment: IV fluids, insulin, potassium replacement, bicarbonate if severe.",
    },
    {
        "id": "emer_006", "name": "Hyperosmolar Hyperglycemic State", "icd10": "E11.0",
        "symptoms": "severe dehydration, altered mental status, seizures, focal neurological deficits, hyperglycemia (often >600 mg/dL), high serum osmolality, no significant ketosis",
        "specialties": "Emergency Medicine, Endocrinology, Critical Care",
        "prevalence": "common", "risk_factors": "Type 2 diabetes, infection, MI, medications (steroids, diuretics), inadequate water intake, elderly",
        "demographics": "elderly with Type 2 diabetes, higher mortality than DKA",
        "red_flags": "altered consciousness, seizures, thromboembolism (high viscosity), mortality 5-20%",
        "urgency": "emergency",
        "description": "Medical emergency with extreme hyperglycemia, hyperosmolality, and dehydration without significant ketosis. Higher mortality than DKA.",
    },
    {
        "id": "emer_007", "name": "Opioid Overdose", "icd10": "T40.1",
        "symptoms": "respiratory depression (slow/absent breathing), pinpoint pupils, decreased consciousness, cyanosis, bradycardia, hypothermia, limp body",
        "specialties": "Emergency Medicine, Toxicology",
        "prevalence": "very common (epidemic)", "risk_factors": "opioid use disorder, prescription opioids, heroin, fentanyl, concurrent benzodiazepine/alcohol use",
        "demographics": "all ages, peak 25-54, males > females",
        "red_flags": "respiratory arrest, cardiac arrest, non-cardiogenic pulmonary edema, rhabdomyolysis",
        "urgency": "emergency",
        "description": "Life-threatening respiratory depression from opioid receptor activation. Treatment: naloxone (Narcan) IV/IM/nasal, airway management, supportive care.",
    },
    {
        "id": "emer_008", "name": "Acetaminophen (Paracetamol) Overdose", "icd10": "T39.1",
        "symptoms": "nausea, vomiting (early), right upper quadrant pain (delayed), jaundice (2-4 days), coagulopathy, hepatic encephalopathy, metabolic acidosis",
        "specialties": "Emergency Medicine, Toxicology, Hepatology",
        "prevalence": "common", "risk_factors": "intentional overdose, accidental (multiple products), chronic alcohol use, malnutrition, enzyme inducers",
        "demographics": "all ages, peak in young adults (intentional), elderly (accidental)",
        "red_flags": "Rumack-Matthew nomogram (>150 mg/L at 4h), INR >1.5, AST >1000, metabolic acidosis, hepatic encephalopathy",
        "urgency": "emergency",
        "description": "Leading cause of acute liver failure in the West. N-acetylcysteine (NAC) is antidote if given within 8 hours.迟发性肝毒性是致命的。",
    },
    {
        "id": "emer_009", "name": "Head Injury (Concussion / TBI)", "icd10": "S06",
        "symptoms": "headache, loss of consciousness, confusion, amnesia (retrograde/anterograde), nausea, vomiting, dizziness, blurred vision, sensitivity to light/noise",
        "specialties": "Emergency Medicine, Neurosurgery, Neurology",
        "prevalence": "very common", "risk_factors": "falls (elderly/children), motor vehicle accidents, sports, violence, assault",
        "demographics": "bimodal: children/young adults and elderly",
        "red_flags": "epidural hematoma (lucid interval), subdural hematoma, intracranial hemorrhage, GCS decline, Cushing reflex",
        "urgency": "emergency",
        "description": "Traumatic brain injury classified by severity (GCS). Most concussions resolve but can lead to post-concussive syndrome. CT needed for significant injuries.",
    },
    {
        "id": "emer_010", "name": "Spinal Cord Injury", "icd10": "S24",
        "symptoms": "loss of motor function, sensory loss, paralysis (paraplegia/tetraplegia), loss of bladder/bowel control, respiratory distress (high cervical), hypotension (spinal shock)",
        "specialties": "Emergency Medicine, Neurosurgery, Orthopedics, Physical Medicine",
        "prevalence": "uncommon", "risk_factors": "motor vehicle accidents (most common), falls, sports (diving, football), violence, osteoporotic fractures",
        "demographics": "males 2:1, peak age 15-30",
        "red_flags": "respiratory failure (C3-C5 phrenic nerve), neurogenic shock, autonomic dysreflexia, spinal instability",
        "urgency": "emergency",
        "description": "Damage to the spinal cord causing loss of function below the level of injury. Complete injury: no function below level. Incomplete: some function preserved.",
    },
    {
        "id": "emer_011", "name": "Burn Injury (Major)", "icd10": "T30",
        "symptoms": "skin erythema, blistering, full-thickness burns, eschar, pain (may be absent in full-thickness), hypovolemic shock, fluid loss, smoke inhalation injury",
        "specialties": "Emergency Medicine, Burn Surgery, Plastic Surgery",
        "prevalence": "common", "risk_factors": "fire, scalding, electrical, chemical, domestic accidents, occupational hazards",
        "demographics": "children (scalds), adults (fire/electrical), elderly (higher mortality)",
        "red_flags": "circumferential burns (compartment syndrome), inhalation injury, airway edema, hypovolemic shock",
        "urgency": "emergency",
        "description": "Classified by depth (superficial, partial, full-thickness) and extent (Rule of Nines for adults, Lund-Browder for children). Major burns require fluid resuscitation.",
    },
    {
        "id": "emer_012", "name": "Sepsis Bundle (Hour-1)", "icd10": "A41",
        "symptoms": "fever or hypothermia, tachycardia, tachypnea, altered mental status, hypotension, elevated lactate, mottled skin, decreased urine output",
        "specialties": "Critical Care, Emergency Medicine, Infectious Disease",
        "prevalence": "very common", "risk_factors": "immunocompromised, indwelling devices, recent surgery, pneumonia, UTI, abdominal infection, skin infection",
        "demographics": "all ages, higher in elderly (>65) and immunocompromised",
        "red_flags": "septic shock, lactate >4 mmol/L, vasopressor requirement, multi-organ dysfunction, mortality 30-50%",
        "urgency": "emergency",
        "description": "Surviving Sepsis Campaign Hour-1 Bundle: obtain cultures, measure lactate, give broad-spectrum antibiotics, 30 mL/kg crystalloid for hypotension, vasopressors if needed.",
    },
    {
        "id": "emer_013", "name": "Hypoglycemia (Severe)", "icd10": "E16.0",
        "symptoms": "confusion, seizures, loss of consciousness, bizarre behavior, combativeness, pallor, diaphoresis, tremor, tachycardia",
        "specialties": "Emergency Medicine, Endocrinology",
        "prevalence": "common", "risk_factors": "insulin use, sulfonylurea use, renal failure, liver disease, alcohol, sepsis, critical illness",
        "demographics": "diabetics on glucose-lowering medications",
        "red_flags": "cardiac arrhythmias, seizures, permanent neurological damage, death",
        "urgency": "emergency",
        "description": "Blood glucose <54 mg/dL with neuroglycopenic symptoms. Severe = requires assistance from others. Treatment: IV dextrose (D50) or glucagon.",
    },
    {
        "id": "emer_014", "name": "Hyperkalemia (Severe)", "icd10": "E87.5",
        "symptoms": "muscle weakness, paresthesias, palpitations, nausea, ECG changes (peaked T waves, widened QRS, sine wave), cardiac arrest",
        "specialties": "Emergency Medicine, Nephrology",
        "prevalence": "common", "risk_factors": "renal failure, ACE inhibitors, ARBs, potassium-sparing diuretics, NSAIDs, potassium supplements, hemolysis, tissue breakdown",
        "demographics": "renal failure patients, elderly on RAAS inhibitors",
        "red_flags": "ECG changes, cardiac arrest, severe muscle weakness",
        "urgency": "emergency",
        "description": "Potassium >5.5 mEq/L. Life-threatening when >6.5 or with ECG changes. Treatment: IV calcium (membrane stabilizer), insulin/glucose, albuterol, kayexalate, dialysis.",
    },
    {
        "id": "emer_015", "name": "Acetaminophen Overdose (Delayed Presentation)", "icd10": "T39.1",
        "symptoms": "initially asymptomatic or mild nausea, then RUQ pain at 24-48h, jaundice at 72-96h, coagulopathy, encephalopathy, metabolic acidosis, multi-organ failure",
        "specialties": "Emergency Medicine, Toxicology, Hepatology, Transplant Surgery",
        "prevalence": "common", "risk_factors": "late presentation (>8h from ingestion), repeat ingestion (staggered), chronic use, alcohol, malnutrition, enzyme inducers",
        "demographics": "all ages",
        "red_flags": "INR >1.5, pH <7.3, creatinine >3.0, Grade III-IV encephalopathy, Kings College criteria for transplant",
        "urgency": "emergency",
        "description": "Delayed acetaminophen toxicity with fulminant hepatic failure. May need liver transplant evaluation. NAC is still beneficial even late.",
    },
]
