"""Endocrine and metabolic diagnoses (ICD-10 chapter IV)."""

ENDOCRINOLOGY_DIAGNOSES: list[dict] = [
    {
        "id": "endo_001", "name": "Diabetes Mellitus Type 2", "icd10": "E11",
        "symptoms": "polyuria, polydipsia, weight loss, fatigue, blurred vision, slow wound healing, recurrent infections, numbness in feet",
        "specialties": "Endocrinology, Internal Medicine",
        "prevalence": "very common (10% of adults)", "risk_factors": "obesity, family history, sedentary lifestyle, age over 45, gestational diabetes, PCOS, ethnicity",
        "demographics": "adults over 45, increasing in younger populations, higher in certain ethnicities",
        "red_flags": "hyperglycemic crisis (DKA, HHS), hypoglycemia, diabetic ketoacidosis, nonketotic hyperosmolar state",
        "urgency": "urgent",
        "description": "Chronic metabolic disorder characterized by insulin resistance and relative insulin deficiency. Leading cause of kidney failure, blindness, and non-traumatic amputation.",
    },
    {
        "id": "endo_002", "name": "Diabetes Mellitus Type 1", "icd10": "E10",
        "symptoms": "polyuria, polydipsia, weight loss, fatigue, blurred vision, bedwetting in children, fruity breath odor, nausea, abdominal pain",
        "specialties": "Endocrinology, Pediatrics",
        "prevalence": "less common (5-10% of diabetes)", "risk_factors": "autoimmune, family history, HLA-DR3/DR4, environmental triggers, early cow's milk exposure (debated)",
        "demographics": "children and young adults, peak onset 4-6 and 10-14 years",
        "red_flags": "diabetic ketoacidosis (DKA), cerebral edema (in children), severe dehydration",
        "urgency": "emergency",
        "description": "Autoimmune destruction of pancreatic beta cells leading to absolute insulin deficiency. Requires lifelong insulin therapy.",
    },
    {
        "id": "endo_003", "name": "Diabetic Ketoacidosis", "icd10": "E11.1",
        "symptoms": "nausea, vomiting, abdominal pain, Kussmaul breathing (deep rapid breathing), fruity breath odor, dehydration, altered mental status, polyuria, polydipsia",
        "specialties": "Emergency Medicine, Endocrinology, Critical Care",
        "prevalence": "common in Type 1 DM", "risk_factors": "Type 1 diabetes, insulin non-compliance, infection, new-onset diabetes, pregnancy",
        "demographics": "Type 1 diabetics, can be initial presentation",
        "red_flags": "altered consciousness, severe acidosis (pH <7.0), hypokalemia, cerebral edema (children)",
        "urgency": "emergency",
        "description": "Life-threatening complication of diabetes with hyperglycemia, ketosis, and metabolic acidosis. Requires aggressive IV fluids and insulin.",
    },
    {
        "id": "endo_004", "name": "Hypoglycemia", "icd10": "E16.2",
        "symptoms": "tremor, sweating, palpitations, hunger, anxiety, confusion, dizziness, blurred vision, seizures, loss of consciousness",
        "specialties": "Endocrinology, Emergency Medicine",
        "prevalence": "common in treated diabetics", "risk_factors": "insulin or sulfonylurea use, missed meals, excessive exercise, alcohol, renal failure, liver disease",
        "demographics": "diabetics on insulin or secretagogues",
        "red_flags": "seizures, loss of consciousness, cardiac arrhythmias, permanent brain damage",
        "urgency": "emergency",
        "description": "Dangerously low blood glucose (<70 mg/dL). Can cause seizures, coma, and death if untreated. Rapid treatment with glucose is essential.",
    },
    {
        "id": "endo_005", "name": "Hyperthyroidism (Graves' Disease)", "icd10": "E05.0",
        "symptoms": "weight loss despite increased appetite, tremor, heat intolerance, sweating, palpitations, anxiety, diarrhea, exophthalmos (Graves'), goiter, insomnia",
        "specialties": "Endocrinology",
        "prevalence": "common", "risk_factors": "female sex, family history, other autoimmune diseases, smoking (Graves' ophthalmopathy), stress",
        "demographics": "females 20-50, peak 30-40",
        "red_flags": "thyroid storm (fever, tachycardia, delirium, heart failure), atrial fibrillation, osteoporosis",
        "urgency": "urgent",
        "description": "Excess thyroid hormone production. Graves' disease is the most common cause, caused by TSH receptor stimulating antibodies.",
    },
    {
        "id": "endo_006", "name": "Hypothyroidism", "icd10": "E03",
        "symptoms": "fatigue, weight gain, cold intolerance, constipation, dry skin, hair loss, depression, menstrual irregularities, myxedema, cognitive slowing, bradycardia",
        "specialties": "Endocrinology",
        "prevalence": "very common", "risk_factors": "Hashimoto thyroiditis (most common), prior thyroid surgery/radiation, lithium, amiodarone, iodine deficiency",
        "demographics": "females 5-10x more, elderly, autoimmune conditions",
        "red_flags": "myxedema coma (hypothermia, altered consciousness, hypoventilation), severe TSH elevation",
        "urgency": "emergency (myxedema coma)",
        "description": "Deficiency of thyroid hormone. Hashimoto thyroiditis is the most common cause in iodine-sufficient areas. Treated with levothyroxine.",
    },
    {
        "id": "endo_007", "name": "Thyroid Storm", "icd10": "E05.5",
        "symptoms": "high fever (>40C), tachycardia, altered mental status (agitation, delirium, psychosis), tremor, diaphoresis, vomiting, diarrhea, jaundice, heart failure",
        "specialties": "Emergency Medicine, Endocrinology, Critical Care",
        "prevalence": "uncommon", "risk_factors": "uncontrolled hyperthyroidism, infection, surgery, trauma, iodine load, radioactive iodine therapy",
        "demographics": "patients with underlying hyperthyroidism",
        "red_flags": "multi-organ failure, cardiovascular collapse, DIC, high mortality (10-30%)",
        "urgency": "emergency",
        "description": "Life-threatening exacerbation of hyperthyroidism with high fever, cardiovascular dysfunction, and altered mental status. Medical emergency.",
    },
    {
        "id": "endo_008", "name": "Cushing's Syndrome", "icd10": "E24",
        "symptoms": "central obesity, moon face, buffalo hump, purple striae, thin skin, easy bruising, proximal muscle weakness, hypertension, hyperglycemia, osteoporosis",
        "specialties": "Endocrinology",
        "prevalence": "uncommon", "risk_factors": "exogenous glucocorticoids (most common), pituitary adenoma (Cushing disease), ectopic ACTH, adrenal tumor",
        "demographics": "adults 20-50, females 3:1",
        "red_flags": "adrenal crisis, severe hypokalemia, psychosis, poor wound healing, infections",
        "urgency": "urgent",
        "description": "Excess cortisol from any cause. Iatrogenic (exogenous steroids) is the most common cause overall. Cushing disease (pituitary ACTH) is the most common endogenous cause.",
    },
    {
        "id": "endo_009", "name": "Addison's Disease (Primary Adrenal Insufficiency)", "icd10": "E27.1",
        "symptoms": "fatigue, weight loss, anorexia, nausea, vomiting, abdominal pain, hyperpigmentation, hypotension, salt craving, dizziness",
        "specialties": "Endocrinology",
        "prevalence": "uncommon", "risk_factors": "autoimmune (most common in developed countries), tuberculosis (most common worldwide), adrenal hemorrhage, metastatic cancer, HIV",
        "demographics": "adults 30-50, females 2:1 for autoimmune",
        "red_flags": "adrenal crisis (severe hypotension, shock, hyponatremia, hyperkalemia), can be fatal if untreated",
        "urgency": "emergency",
        "description": "Insufficient cortisol and aldosterone production from the adrenal glands. Autoimmune adrenalitis is the most common cause in developed countries.",
    },
    {
        "id": "endo_010", "name": "Adrenal Crisis", "icd10": "E27.2",
        "symptoms": "severe hypotension, shock, abdominal pain, nausea, vomiting, confusion, weakness, hyponatremia, hyperkalemia, hypoglycemia, fever",
        "specialties": "Emergency Medicine, Endocrinology, Critical Care",
        "prevalence": "uncommon", "risk_factors": "chronic steroid use with abrupt withdrawal, untreated Addison's, surgery, infection, trauma",
        "demographics": "any age, patients on chronic glucocorticoids",
        "red_flags": "refractory hypotension, cardiovascular collapse, death without treatment",
        "urgency": "emergency",
        "description": "Life-threatening acute adrenal insufficiency requiring immediate IV hydrocortisone and fluids. Can occur in patients on chronic steroids.",
    },
    {
        "id": "endo_011", "name": "Hyperparathyroidism", "icd10": "E21.1",
        "symptoms": "bone pain, kidney stones, abdominal pain, constipation, fatigue, depression, confusion, polyuria, polydipsia, osteoporosis",
        "specialties": "Endocrinology, General Surgery",
        "prevalence": "common in elderly", "risk_factors": "solitary adenoma (85%), MEN syndromes, prior radiation, lithium use",
        "demographics": "postmenopausal women most common",
        "red_flags": "hypercalcemic crisis (severe hypercalcemia, altered consciousness, renal failure)",
        "urgency": "urgent",
        "description": "Excess parathyroid hormone causing hypercalcemia. Remember the mnemonic: 'bones, stones, abdominal moans, and psychic groans'.",
    },
    {
        "id": "endo_012", "name": "Hypoparathyroidism", "icd10": "E20",
        "symptoms": "tingling around mouth, muscle cramps, carpopedal spasm, seizures, fatigue, anxiety, dry skin, brittle nails, cataracts",
        "specialties": "Endocrinology",
        "prevalence": "uncommon", "risk_factors": "post-thyroidectomy (most common), autoimmune, DiGeorge syndrome, hypomagnesemia, radiation",
        "demographics": "adults post-thyroid/neck surgery",
        "red_flags": "laryngospasm, seizures, QT prolongation, cardiac arrhythmias",
        "urgency": "urgent",
        "description": "Insufficient parathyroid hormone causing hypocalcemia. Most commonly iatrogenic after thyroid or parathyroid surgery.",
    },
    {
        "id": "endo_013", "name": "Diabetes Insipidus", "icd10": "E23.2",
        "symptoms": "massive polyuria (dilute urine), extreme polydipsia, nocturia, dehydration, fatigue, irritability, constipation",
        "specialties": "Endocrinology, Nephrology",
        "prevalence": "uncommon", "risk_factors": "head trauma/surgery (central), lithium (nephrogenic), pituitary tumors, pregnancy (gestational), idiopathic",
        "demographics": "any age, depends on etiology",
        "red_flags": "severe dehydration, hypernatremia, altered mental status, cardiovascular collapse",
        "urgency": "urgent",
        "description": "Deficiency of ADH (central) or resistance to ADH (nephrogenic) causing inability to concentrate urine. Results in massive dilute urine output.",
    },
    {
        "id": "endo_014", "name": "Hyperaldosteronism (Conn's Syndrome)", "icd10": "E26.0",
        "symptoms": "hypertension, hypokalemia, muscle weakness, polyuria, polydipsia, headache, fatigue, metabolic alkalosis",
        "specialties": "Endocrinology, Hypertension",
        "prevalence": "moderate (5-10% of hypertensives)", "risk_factors": "adrenal adenoma (unilateral), bilateral adrenal hyperplasia",
        "demographics": "adults 30-50, females 2:1 for adenoma",
        "red_flags": "severe hypokalemia, arrhythmias, malignant hypertension",
        "urgency": "urgent",
        "description": "Excess aldosterone from the adrenal glands causing hypertension and hypokalemia. The most common cause of secondary hypertension.",
    },
    {
        "id": "endo_015", "name": "Metabolic Syndrome", "icd10": "E88.8",
        "symptoms": "central obesity, elevated triglycerides, low HDL, elevated blood pressure, elevated fasting glucose, insulin resistance, acanthosis nigricans",
        "specialties": "Endocrinology, Internal Medicine",
        "prevalence": "very common (35% of US adults)", "risk_factors": "obesity (abdominal), sedentary lifestyle, unhealthy diet, insulin resistance, genetic predisposition",
        "demographics": "adults over 40, increasing in younger populations, higher in certain ethnicities",
        "red_flags": "progression to diabetes, cardiovascular events, NAFLD/NASH",
        "urgency": "routine",
        "description": "Cluster of metabolic abnormalities (central obesity, dyslipidemia, hypertension, hyperglycemia) that increase cardiovascular and diabetes risk.",
    },
]
