"""Gastrointestinal system diagnoses (ICD-10 chapter XI)."""

GASTRO_DIAGNOSES: list[dict] = [
    {
        "id": "gastro_001", "name": "Acute Appendicitis", "icd10": "K35",
        "symptoms": "periumbilical pain migrating to right lower quadrant, nausea, vomiting, fever, anorexia, rebound tenderness, guarding, McBurney point tenderness",
        "specialties": "General Surgery, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "age 10-30, male sex slightly, family history, low-fiber diet",
        "demographics": "peak incidence 10-30 years",
        "red_flags": "perforation (rigid abdomen, diffuse tenderness), abscess, peritonitis, sepsis",
        "urgency": "emergency",
        "description": "Inflammation of the appendix, the most common surgical emergency. Classic presentation: periumbilical pain migrating to RLQ with nausea and fever.",
    },
    {
        "id": "gastro_002", "name": "Acute Pancreatitis", "icd10": "K85",
        "symptoms": "severe epigastric pain radiating to back, nausea, vomiting, fever, tachycardia, abdominal tenderness, guarding, elevated amylase and lipase",
        "specialties": "Gastroenterology, General Surgery",
        "prevalence": "common", "risk_factors": "gallstones (40%), alcohol (30%), hypertriglyceridemia, medications, ERCP, trauma",
        "demographics": "adults 35-75, depends on etiology",
        "red_flags": "organ failure, necrotizing pancreatitis, infected necrosis, pancreatic pseudocyst, abscess",
        "urgency": "emergency",
        "description": "Inflammation of the pancreas ranging from mild edematous to severe necrotizing. Diagnosis: 2 of 3 (characteristic pain, elevated lipase >3x, imaging findings).",
    },
    {
        "id": "gastro_003", "name": "Peptic Ulcer Disease", "icd10": "K27",
        "symptoms": "epigastric pain, burning pain relieved by food (gastric) or worsened by food (duodenal), nausea, bloating, early satiety, hematemesis, melena",
        "specialties": "Gastroenterology",
        "prevalence": "very common", "risk_factors": "H. pylori infection, NSAID use, smoking, alcohol, stress, family history, age >60",
        "demographics": "adults, duodenal ulcers peak 30-50, gastric ulcers peak 55-70",
        "red_flags": "hematemesis, melena, perforation (sudden severe pain, rigid abdomen), gastric outlet obstruction",
        "urgency": "urgent",
        "description": "Defect in the gastric or duodenal mucosa from acid damage. Most common causes: H. pylori and NSAIDs. Can cause bleeding, perforation, or obstruction.",
    },
    {
        "id": "gastro_004", "name": "Gastrointestinal Bleeding (Upper)", "icd10": "K92.2",
        "symptoms": "hematemesis (bright red or coffee-ground), melena (black tarry stool), hematochezia (if severe), dizziness, syncope, tachycardia, hypotension, pallor",
        "specialties": "Gastroenterology, Emergency Medicine",
        "prevalence": "common", "risk_factors": "peptic ulcer, varices (cirrhosis), Mallory-Weiss tear, gastritis, anticoagulant use, NSAIDs",
        "demographics": "adults, elderly at higher risk of adverse outcomes",
        "red_flags": "hemodynamic instability, ongoing bleeding, large variceal bleed, re-bleeding risk",
        "urgency": "emergency",
        "description": "Bleeding from the GI tract proximal to the ligament of Treitz. Can range from occult to life-threatening hemorrhage.",
    },
    {
        "id": "gastro_005", "name": "Lower GI Bleeding", "icd10": "K92.2",
        "symptoms": "hematochezia (bright red blood per rectum), maroon stool, dizziness, tachycardia, hypotension, abdominal pain, tenesmus",
        "specialties": "Gastroenterology, Colorectal Surgery, Emergency Medicine",
        "prevalence": "common", "risk_factors": "diverticulosis (most common), angiodysplasia, colorectal cancer, IBD, ischemic colitis, hemorrhoids",
        "demographics": "elderly over 60 (diverticulosis), any age with IBD",
        "red_flags": "massive hemorrhage, hemodynamic instability, ongoing transfusion requirements",
        "urgency": "emergency",
        "description": "Bleeding from the GI tract distal to the ligament of Treitz. Diverticulosis is the most common cause in adults.",
    },
    {
        "id": "gastro_006", "name": "Cholecystitis (Acute)", "icd10": "K81.0",
        "symptoms": "right upper quadrant pain, fever, nausea, vomiting, Murphy sign (inspiratory arrest during RUQ palpation), abdominal tenderness, leukocytosis",
        "specialties": "General Surgery, Gastroenterology",
        "prevalence": "very common", "risk_factors": "gallstones, female sex, obesity, 40s, fair complexion, fertile, multiple pregnancies (5 Fs)",
        "demographics": "females 40-60, overweight",
        "red_flags": "gangrenous cholecystitis, emphysematous cholecystitis, perforation, cholangitis (Charcot triad), sepsis",
        "urgency": "emergency",
        "description": "Inflammation of the gallbladder, usually from gallstone obstruction of the cystic duct. Requires cholecystectomy.",
    },
    {
        "id": "gastro_007", "name": "Cholangitis", "icd10": "K83.0",
        "symptoms": "fever, jaundice, right upper quadrant pain (Charcot triad), nausea, vomiting, dark urine, pale stools, pruritus, hypotension (Reynolds pentad)",
        "specialties": "Gastroenterology, General Surgery",
        "prevalence": "moderate", "risk_factors": "gallstones, biliary strictures, biliary stent, parasitic infection",
        "demographics": "adults with biliary disease",
        "red_flags": "Reynolds pentad (Charcot triad + hypotension + confusion), septic shock, liver abscess",
        "urgency": "emergency",
        "description": "Infection of the biliary tract from bile duct obstruction. Requires emergent biliary decompression (ERCP or percutaneous drainage).",
    },
    {
        "id": "gastro_008", "name": "Inflammatory Bowel Disease (Crohn's)", "icd10": "K50",
        "symptoms": "abdominal pain, diarrhea (may be bloody), weight loss, fatigue, fever, perianal disease, mouth ulcers, joint pain, skin lesions",
        "specialties": "Gastroenterology",
        "prevalence": "moderate", "risk_factors": "family history, smoking, Caucasian, urban/developed countries, appendectomy (protective), NSAIDs",
        "demographics": "bimodal: 15-30 and 50-70, equal sex distribution",
        "red_flags": "bowel obstruction, perforation, abscess, fistula, toxic megacolon, colorectal cancer risk",
        "urgency": "urgent",
        "description": "Chronic inflammatory bowel disease with transmural, skip lesions anywhere from mouth to anus. Most commonly affects terminal ileum.",
    },
    {
        "id": "gastro_009", "name": "Inflammatory Bowel Disease (Ulcerative Colitis)", "icd10": "K51",
        "symptoms": "bloody diarrhea, urgency, tenesmus, abdominal pain (left lower quadrant), weight loss, fatigue, rectal bleeding",
        "specialties": "Gastroenterology",
        "prevalence": "moderate", "risk_factors": "family history, Caucasian, urban/developed countries, smoking (protective for UC but harmful overall)",
        "demographics": "bimodal: 15-30 and 50-70, slight male predominance",
        "red_flags": "toxic megacolon, massive hemorrhage, perforation, colorectal cancer (increases with disease duration)",
        "urgency": "urgent",
        "description": "Chronic inflammatory bowel disease limited to the colon and rectum with continuous mucosal inflammation. Always involves the rectum.",
    },
    {
        "id": "gastro_010", "name": "Diverticulitis", "icd10": "K57",
        "symptoms": "left lower quadrant pain, fever, nausea, vomiting, change in bowel habits, abdominal tenderness, leukocytosis, bloating",
        "specialties": "Gastroenterology, General Surgery",
        "prevalence": "very common in elderly", "risk_factors": "low-fiber diet, age over 50, obesity, sedentary lifestyle, smoking, NSAIDs",
        "demographics": "adults over 50, increases with age",
        "red_flags": "complicated diverticulitis (abscess, perforation, peritonitis, fistula), sepsis, obstruction",
        "urgency": "urgent",
        "description": "Inflammation of colonic diverticula (outpouchings). Most common in the sigmoid colon. Uncomplicated managed with antibiotics; complicated may need surgery.",
    },
    {
        "id": "gastro_011", "name": "Bowel Obstruction (Small Bowel)", "icd10": "K56.6",
        "symptoms": "colicky abdominal pain, vomiting (bilious), abdominal distension, constipation/obstipation, high-pitched bowel sounds, inability to pass flatus",
        "specialties": "General Surgery, Emergency Medicine",
        "prevalence": "common", "risk_factors": "adhesions (most common, prior surgery), hernia, malignancy, volvulus, intussusception (children)",
        "demographics": "adults with prior abdominal surgery (adhesions), elderly (malignancy)",
        "red_flags": "strangulation (constant pain, fever, peritonitis), ischemia, perforation, sepsis",
        "urgency": "emergency",
        "description": "Blockage of the small intestine preventing passage of intestinal contents. Adhesions from prior surgery are the most common cause.",
    },
    {
        "id": "gastro_012", "name": "Esophageal Variceal Bleeding", "icd10": "I98.2",
        "symptoms": "massive hematemesis, melena, dizziness, syncope, tachycardia, hypotension, signs of chronic liver disease (jaundice, ascites, spider angiomata)",
        "specialties": "Gastroenterology, Hepatology, Emergency Medicine",
        "prevalence": "moderate in cirrhotics", "risk_factors": "portal hypertension, cirrhosis, alcohol, hepatitis B/C",
        "demographics": "adults with advanced liver disease",
        "red_flags": "hemodynamic instability, recurrent bleeding, Child-Pugh C, MELD >20",
        "urgency": "emergency",
        "description": "Bleeding from dilated esophageal veins due to portal hypertension. High mortality if untreated. Emergent endoscopy with band ligation is the standard.",
    },
    {
        "id": "gastro_013", "name": "Celiac Disease", "icd10": "K90.0",
        "symptoms": "chronic diarrhea, bloating, weight loss, iron deficiency anemia, fatigue, dermatitis herpetiformis, mouth ulcers, failure to thrive (children)",
        "specialties": "Gastroenterology",
        "prevalence": "moderate (1 in 100)", "risk_factors": "HLA-DQ2/DQ8, family history, Type 1 diabetes, Down syndrome, Turner syndrome",
        "demographics": "any age, peak diagnosis in 40s, slight female predominance",
        "red_flags": "refractory celiac disease, T-cell lymphoma, severe malnutrition, osteoporosis",
        "urgency": "routine",
        "description": "Autoimmune enteropathy triggered by gluten ingestion in genetically susceptible individuals. Causes villous atrophy of the small intestine.",
    },
    {
        "id": "gastro_014", "name": "Irritable Bowel Syndrome", "icd10": "K58",
        "symptoms": "abdominal pain relieved by defecation, altered bowel habits (diarrhea, constipation, or mixed), bloating, urgency, mucus in stool, incomplete evacuation",
        "specialties": "Gastroenterology",
        "prevalence": "very common (10-15% of adults)", "risk_factors": "female sex, stress, prior GI infection, anxiety/depression, food triggers",
        "demographics": "females 2:1, onset typically under 50",
        "red_flags": "alarm features: rectal bleeding, weight loss, anemia, nocturnal symptoms, family history of CRC, onset after 50",
        "urgency": "routine",
        "description": "Functional GI disorder with recurrent abdominal pain and altered bowel habits without structural abnormality. Rome IV criteria used for diagnosis.",
    },
    {
        "id": "gastro_015", "name": "Hepatitis (Viral, Acute)", "icd10": "B15-B19",
        "symptoms": "jaundice, dark urine, pale stools, fatigue, nausea, vomiting, abdominal pain (RUQ), fever, pruritus, hepatomegaly",
        "specialties": "Gastroenterology, Hepatology, Infectious Disease",
        "prevalence": "common worldwide", "risk_factors": "Hepatitis A: contaminated food/water; Hep B/C: blood/body fluids, IV drug use, sexual contact",
        "demographics": "depends on type, Hep A more in developing countries, Hep B/C worldwide",
        "red_flags": "fulminant hepatic failure (coagulopathy, encephalopathy), acute liver failure, chronic hepatitis B/C progression",
        "urgency": "urgent",
        "description": "Inflammation of the liver from viral infection. Five types (A-E) with different transmission routes and outcomes.",
    },
    {
        "id": "gastro_016", "name": "Cirrhosis (Decompensated)", "icd10": "K74.6",
        "symptoms": "jaundice, ascites, peripheral edema, encephalopathy, variceal bleeding, spider angiomata, palmar erythema, gynecomastia, caput medusae, pruritus",
        "specialties": "Hepatology, Gastroenterology",
        "prevalence": "common", "risk_factors": "alcohol, chronic hepatitis B/C, NAFLD/NASH, autoimmune hepatitis, hemochromatosis, Wilson disease",
        "demographics": "adults 40-70, males more for alcohol-related",
        "red_flags": "variceal hemorrhage, spontaneous bacterial peritonitis, hepatorenal syndrome, hepatocellular carcinoma, hepatic encephalopathy",
        "urgency": "emergency",
        "description": "End-stage liver disease with fibrosis and nodular regeneration. Decompensation indicated by ascites, variceal bleeding, encephalopathy, or jaundice.",
    },
    {
        "id": "gastro_017", "name": "GERD (Gastroesophageal Reflux Disease)", "icd10": "K21",
        "symptoms": "heartburn, acid regurgitation, chest pain, dysphagia, chronic cough, laryngitis, asthma-like symptoms, dental erosion",
        "specialties": "Gastroenterology",
        "prevalence": "very common", "risk_factors": "obesity, hiatal hernia, pregnancy, smoking, fatty/spicy foods, caffeine, alcohol",
        "demographics": "adults of all ages, increases with age",
        "red_flags": "Barrett's esophagus (dysplasia), esophageal stricture, esophageal adenocarcinoma alarm symptoms (dysphagia, weight loss, bleeding)",
        "urgency": "routine",
        "description": "Chronic condition where stomach acid flows back into the esophagus causing symptoms and complications. Most common GI diagnosis in outpatient settings.",
    },
    {
        "id": "gastro_018", "name": "Colorectal Cancer", "icd10": "C18-C20",
        "symptoms": "change in bowel habits, rectal bleeding, blood in stool, abdominal pain, weight loss, iron deficiency anemia, fatigue, tenesmus, bowel obstruction",
        "specialties": "Gastroenterology, Colorectal Surgery, Oncology",
        "prevalence": "common", "risk_factors": "age over 50, polyps, IBD, family history, Lynch syndrome, FAP, low-fiber diet, obesity, smoking, alcohol",
        "demographics": "adults over 50, slight male predominance, increasing in younger adults",
        "red_flags": "bowel obstruction, perforation, liver metastases, iron deficiency anemia",
        "urgency": "urgent",
        "description": "Third most common cancer worldwide. Develops from adenomatous polyps over 10-15 years. Screening colonoscopy is key to prevention.",
    },
    {
        "id": "gastro_019", "name": "Gastroparesis", "icd10": "K31.4",
        "symptoms": "early satiety, postprandial fullness, nausea, vomiting of undigested food, bloating, abdominal pain, weight loss,GERD symptoms",
        "specialties": "Gastroenterology",
        "prevalence": "moderate", "risk_factors": "diabetes (most common), post-surgical, idiopathic, medications (opioids, anticholinergics), Parkinson's disease",
        "demographics": "females 2:1, ages 20-50",
        "red_flags": "severe dehydration, malnutrition, bezoar formation, erratic glucose control in diabetics",
        "urgency": "urgent",
        "description": "Delayed gastric emptying without mechanical obstruction. Most common cause is diabetic autonomic neuropathy.",
    },
    {
        "id": "gastro_020", "name": "Acute Mesenteric Ischemia", "icd10": "K55.0",
        "symptoms": "severe abdominal pain out of proportion to exam, nausea, vomiting, bloody diarrhea, abdominal distension, metabolic acidosis, fever",
        "specialties": "General Surgery, Vascular Surgery, Emergency Medicine",
        "prevalence": "uncommon", "risk_factors": "atrial fibrillation, atherosclerosis, heart failure, hypotension, hypercoagulable states, oral contraceptives",
        "demographics": "elderly over 60, cardiac patients",
        "red_flags": "pain out of proportion to exam (classic), peritoneal signs (bowel infarction), sepsis, metabolic acidosis",
        "urgency": "emergency",
        "description": "Acute reduction of blood flow to the intestines. Most commonly from arterial embolism (mesenteric artery). Very high mortality if not treated promptly.",
    },
]
