"""Infectious disease diagnoses (ICD-10 chapter I)."""

INFECTIOUS_DIAGNOSES: list[dict] = [
    {
        "id": "inf_001", "name": "Sepsis / Septic Shock", "icd10": "A41",
        "symptoms": "fever, hypothermia, tachycardia, tachypnea, altered mental status, hypotension, mottled skin, decreased urine output, leukocytosis or leukopenia",
        "specialties": "Critical Care, Infectious Disease, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "immunosuppression, indwelling catheters, recent surgery, diabetes, chronic illness, burns, trauma",
        "demographics": "all ages, higher in elderly and immunocompromised",
        "red_flags": "septic shock (vasopressor requirement, lactate >4), multi-organ failure, DIC, mortality 30-50%",
        "urgency": "emergency",
        "description": "Life-threatening organ dysfunction from dysregulated host response to infection. Hour-1 bundle: antibiotics, fluids, lactate, cultures.",
    },
    {
        "id": "inf_002", "name": "HIV/AIDS", "icd10": "B20",
        "symptoms": "weight loss, chronic diarrhea, oral thrush, recurrent infections, fatigue, lymphadenopathy, night sweats, skin manifestations, opportunistic infections",
        "specialties": "Infectious Disease",
        "prevalence": "common worldwide", "risk_factors": "sexual contact, IV drug use, blood products, vertical transmission, occupational exposure",
        "demographics": "all ages, higher prevalence in sub-Saharan Africa, MSM, IV drug users",
        "red_flags": "AIDS-defining illness (PCP pneumonia, toxoplasmosis, CMV retinitis, Kaposi sarcoma, lymphoma), severe immunosuppression (CD4 <200)",
        "urgency": "urgent",
        "description": "Human Immunodeficiency Virus infection leading to progressive immune deficiency. Without treatment, progresses to AIDS with opportunistic infections.",
    },
    {
        "id": "inf_003", "name": "Malaria (Falciparum)", "icd10": "B54",
        "symptoms": "high fever with chills, rigors, headache, myalgia, vomiting, diarrhea, anemia, jaundice, splenomegaly, hemoglobinuria (blackwater fever)",
        "specialties": "Infectious Disease, Tropical Medicine",
        "prevalence": "very common in endemic areas", "risk_factors": "travel to endemic areas (sub-Saharan Africa, SE Asia), no chemoprophylaxis, outdoor sleeping",
        "demographics": "all ages in endemic areas, children under 5 most vulnerable, pregnant women",
        "red_flags": "cerebral malaria (seizures, coma), severe anemia, hypoglycemia, ARDS, renal failure, DIC, death",
        "urgency": "emergency",
        "description": "Parasitic infection (Plasmodium falciparum) transmitted by Anopheles mosquito. Most severe form can cause cerebral malaria and death.",
    },
    {
        "id": "inf_004", "name": "Pneumonia (Atypical / Legionella)", "icd10": "J15.7",
        "symptoms": "cough, fever, headache, myalgia, confusion, diarrhea, hyponatremia, elevated LFTs, relative bradycardia",
        "specialties": "Infectious Disease, Pulmonology",
        "prevalence": "moderate", "risk_factors": "air conditioning systems, water systems, immunosuppression, smoking, chronic lung disease, age >50",
        "demographics": "adults, males more, elderly higher risk",
        "red_flags": "respiratory failure, hyponatremia, confusion, multi-organ involvement, high mortality",
        "urgency": "emergency",
        "description": "Pneumonia caused by Legionella pneumophila, transmitted through contaminated water systems. Can cause severe disease with extrapulmonary manifestations.",
    },
    {
        "id": "inf_005", "name": "Cellulitis", "icd10": "L03",
        "symptoms": "red, warm, swollen, tender skin, spreading erythema, fever, chills, lymphangitis, regional lymphadenopathy",
        "specialties": "Infectious Disease, Emergency Medicine, Dermatology",
        "prevalence": "very common", "risk_factors": "skin break (cut, insect bite, surgical wound), edema, lymphedema, tinea pedis, diabetes, immunosuppression, IV drug use",
        "demographics": "all ages, more common in males, elderly, obese, diabetic",
        "red_flags": "necrotizing fasciitis (pain out of proportion, crepitus, systemic toxicity), sepsis, abscess",
        "urgency": "urgent",
        "description": "Bacterial infection of the dermis and subcutaneous tissue. Most commonly caused by Streptococcus pyogenes and Staphylococcus aureus.",
    },
    {
        "id": "inf_006", "name": "Necrotizing Fasciitis", "icd10": "M72.6",
        "symptoms": "severe pain out of proportion to examination, swelling, erythema, crepitus, bullae, skin necrosis, fever, tachycardia, hypotension, toxicity",
        "specialties": "Infectious Disease, General Surgery, Critical Care",
        "prevalence": "uncommon", "risk_factors": "diabetes, immunosuppression, IV drug use, trauma, surgery, peripheral vascular disease",
        "demographics": "adults with comorbidities",
        "red_flags": "pain out of proportion, crepitus, systemic toxicity, shock, gas in tissues on imaging",
        "urgency": "emergency",
        "description": "Rapidly progressive, deep soft tissue infection with extensive necrosis. Polymicrobial or monomicrobial (Group A Strep). Requires emergent surgical debridement.",
    },
    {
        "id": "inf_007", "name": "Meningococcal Meningitis", "icd10": "A39.0",
        "symptoms": "fever, severe headache, neck stiffness, photophobia, petechial/purpuric rash, nausea, vomiting, altered mental status, seizures",
        "specialties": "Infectious Disease, Emergency Medicine, Neurology",
        "prevalence": "moderate (outbreaks)", "risk_factors": "college dormitory, complement deficiency, asplenia, travel to meningitis belt, close contacts",
        "demographics": "children and young adults, peaks in adolescence",
        "red_flags": "Waterhouse-Friderichsen syndrome (adrenal hemorrhage, DIC, shock), purpura fulminans, septic shock",
        "urgency": "emergency",
        "description": "Bacterial meningitis caused by Neisseria meningitidis. Can cause fulminant sepsis with DIC and adrenal hemorrhage. Vaccine preventable.",
    },
    {
        "id": "inf_008", "name": "Infective Endocarditis", "icd10": "I33",
        "symptoms": "fever, chills, night sweats, new murmur, splinter hemorrhages, Osler nodes, Janeway lesions, Roth spots, embolic events, weight loss, fatigue",
        "specialties": "Infectious Disease, Cardiology",
        "prevalence": "uncommon", "risk_factors": "prosthetic valve, IV drug use, dental procedures, poor dental hygiene, indwelling catheters",
        "demographics": "IV drug users (right-sided), elderly with valvular disease (left-sided)",
        "red_flags": "heart failure from valvular destruction, septic emboli, mycotic aneurysm, splenic abscess, vertebral osteomyelitis",
        "urgency": "emergency",
        "description": "Infection of the endocardial surface, most commonly heart valves. Can be acute (S. aureus) or subacute (viridans streptococci).",
    },
    {
        "id": "inf_009", "name": "Tuberculosis (Extrapulmonary)", "icd10": "A16-A19",
        "symptoms": "depends on site: lymphadenitis (cervical lymphadenopathy), pleural (effusion), meningitis (headache, altered consciousness), vertebral (Pott disease), renal (hematuria)",
        "specialties": "Infectious Disease, Pulmonology",
        "prevalence": "common worldwide", "risk_factors": "endemic areas, HIV, immunosuppression, close contact, malnutrition, homelessness",
        "demographics": "all ages, higher in developing countries",
        "red_flags": "TB meningitis (high mortality), miliary TB, Pott disease with cord compression, drug-resistant TB",
        "urgency": "urgent",
        "description": "Tuberculosis affecting sites outside the lungs. Can involve virtually any organ. Lymph node TB is the most common form of extrapulmonary TB.",
    },
    {
        "id": "inf_010", "name": "COVID-19 (Severe)", "icd10": "U07.1",
        "symptoms": "fever, cough, shortness of breath, fatigue, loss of taste/smell, myalgia, headache, pneumonia, ARDS, thromboembolic events, cytokine storm",
        "specialties": "Infectious Disease, Pulmonology, Critical Care",
        "prevalence": "pandemic", "risk_factors": "age over 65, obesity, diabetes, cardiovascular disease, immunosuppression, chronic lung disease",
        "demographics": "all ages, severity increases with age and comorbidities",
        "red_flags": "ARDS, cytokine storm, pulmonary embolism, myocarditis, MIS-C (children), long COVID",
        "urgency": "emergency",
        "description": "Coronavirus disease 2019 caused by SARS-CoV-2. Ranges from asymptomatic to fatal. Severe cases involve ARDS, cytokine storm, and thromboembolic complications.",
    },
    {
        "id": "inf_011", "name": "Hepatitis B (Chronic)", "icd10": "B18.1",
        "symptoms": "fatigue, mild jaundice, right upper quadrant discomfort, dark urine, hepatomegaly, many are asymptomatic for years",
        "specialties": "Hepatology, Infectious Disease, Gastroenterology",
        "prevalence": "common worldwide (296 million)", "risk_factors": "vertical transmission (perinatal), blood/body fluid exposure, IV drug use, sexual contact, endemic areas",
        "demographics": "all ages, highest chronicity if acquired perinatal (>90%)",
        "red_flags": "cirrhosis, hepatocellular carcinoma, fulminant hepatitis, extrahepatic manifestations (glomerulonephritis, vasculitis)",
        "urgency": "routine to urgent",
        "description": "Hepatitis B virus infection that persists beyond 6 months. Can lead to cirrhosis and hepatocellular carcinoma. Preventable by vaccination.",
    },
    {
        "id": "inf_012", "name": "Urinary Tract Infection (Cystitis)", "icd10": "N30",
        "symptoms": "dysuria, frequency, urgency, suprapubic pain, hematuria, cloudy urine, foul-smelling urine, no fever",
        "specialties": "Primary Care, Urology",
        "prevalence": "very common", "risk_factors": "female sex, sexual activity, spermicide use, prior UTIs, menopause, urinary catheter",
        "demographics": "females 20-50, 50-60% will have at least one UTI",
        "red_flags": "fever (suggests pyelonephritis), back/flank pain, nausea/vomiting, immunosuppression",
        "urgency": "routine",
        "description": "Infection of the bladder mucosa. The most common bacterial infection in females. E. coli causes 80-90% of cases.",
    },
    {
        "id": "inf_013", "name": "Clostridioides Difficile Infection", "icd10": "A04.7",
        "symptoms": "watery diarrhea (≥3 stools/day), abdominal cramping, fever, nausea, loss of appetite, leukocytosis, pseudomembranous colitis",
        "specialties": "Infectious Disease, Gastroenterology",
        "prevalence": "common", "risk_factors": "recent antibiotics (clindamycin, fluoroquinolones, cephalosporins), PPI use, hospitalization, age >65, prior CDI",
        "demographics": "elderly, hospitalized patients, antibiotic users",
        "red_flags": "fulminant colitis, toxic megacolon, colonic perforation, sepsis, colectomy",
        "urgency": "urgent",
        "description": "Infection with toxin-producing Clostridioides difficile, typically after antibiotic disruption of normal gut flora. Leading cause of healthcare-associated diarrhea.",
    },
    {
        "id": "inf_014", "name": "Lyme Disease", "icd10": "A69.2",
        "symptoms": "erythema migrans (bull's-eye rash), fever, headache, fatigue, myalgia, arthralgia, regional lymphadenopathy, neck stiffness",
        "specialties": "Infectious Disease",
        "prevalence": "common in endemic areas", "risk_factors": "tick exposure (Ixodes), outdoor activities, endemic areas (Northeast US, Europe)",
        "demographics": "all ages, outdoor workers, children",
        "red_flags": "Lyme carditis (heart block), Lyme meningitis, facial palsy (bilateral), Lyme arthritis, encephalopathy",
        "urgency": "urgent",
        "description": "Tick-borne spirochete infection (Borrelia burgdorferi). Early localized: erythema migrans. Late disseminated: neurological, cardiac, and joint involvement.",
    },
    {
        "id": "inf_015", "name": "Tetanus", "icd10": "A35",
        "symptoms": "trismus (lockjaw), neck stiffness, dysphagia, opisthotonus, muscle spasms, risus sardonicus, autonomic instability, hypertension, tachycardia",
        "specialties": "Infectious Disease, Critical Care, Emergency Medicine",
        "prevalence": "uncommon (vaccine preventable)", "risk_factors": "puncture wounds, rusty objects, soil contamination, unvaccinated or under-vaccinated",
        "demographics": "unvaccinated individuals, neonates in developing countries",
        "red_flags": "respiratory failure from laryngospasm or diaphragm spasm, autonomic instability, aspiration",
        "urgency": "emergency",
        "description": "Clostridium tetani toxin causes severe muscle spasms. One of the most painful infectious diseases. Mortality 10-20% even with treatment.",
    },
]
