"""Renal and urinary system diagnoses (ICD-10 chapter XIV)."""

NEPHROLOGY_DIAGNOSES: list[dict] = [
    {
        "id": "neph_001", "name": "Acute Kidney Injury", "icd10": "N17",
        "symptoms": "decreased urine output, oliguria, edema, fatigue, nausea, vomiting, confusion, shortness of breath, seizures, uremic frost",
        "specialties": "Nephrology, Internal Medicine, Critical Care",
        "prevalence": "common", "risk_factors": "sepsis, dehydration, nephrotoxic drugs (NSAIDs, aminoglycosides), heart failure, contrast dye, obstruction",
        "demographics": "all ages, higher risk in elderly and those with CKD",
        "red_flags": "anuria, hyperkalemia (cardiac arrest), severe metabolic acidosis, pulmonary edema, uremic encephalopathy",
        "urgency": "emergency",
        "description": "Rapid decline in kidney function causing accumulation of waste products and fluid imbalance. Classified by KDIGO criteria (staging by creatinine rise and urine output).",
    },
    {
        "id": "neph_002", "name": "Chronic Kidney Disease", "icd10": "N18",
        "symptoms": "fatigue, edema, anorexia, nausea, pruritus, nocturia, polyuria, muscle cramps, cognitive impairment, restless legs",
        "specialties": "Nephrology",
        "prevalence": "very common (15% of adults)", "risk_factors": "diabetes (leading cause), hypertension (second leading), glomerulonephritis, polycystic kidney disease",
        "demographics": "elderly, higher in African Americans, Hispanics, Native Americans",
        "red_flags": "uremic pericarditis, severe anemia, bone disease, metabolic acidosis, hyperkalemia, approach to dialysis",
        "urgency": "urgent",
        "description": "Progressive loss of kidney function over months to years. 5 stages based on GFR. Leading causes: diabetes and hypertension.",
    },
    {
        "id": "neph_003", "name": "Nephrotic Syndrome", "icd10": "N04",
        "symptoms": "massive proteinuria, edema (peripheral and periorbital), foamy urine, hypoalbuminemia, hyperlipidemia, fatigue, weight gain",
        "specialties": "Nephrology",
        "prevalence": "moderate", "risk_factors": "minimal change disease (children), membranous nephropathy (adults), diabetic nephropathy, lupus nephritis",
        "demographics": "children (minimal change), adults 40-60 (membranous)",
        "red_flags": "thromboembolism (renal vein thrombosis, DVT/PE), infection (peritonitis), acute kidney injury",
        "urgency": "urgent",
        "description": "Kidney disorder with massive proteinuria (>3.5g/day), hypoalbuminemia, edema, and hyperlipidemia. Increased risk of thrombosis and infection.",
    },
    {
        "id": "neph_004", "name": "Glomerulonephritis (Acute Post-Infectious)", "icd10": "N00",
        "symptoms": "hematuria (cola-colored urine), edema, hypertension, oliguria, proteinuria, malaise, fever, flank pain",
        "specialties": "Nephrology",
        "prevalence": "moderate", "risk_factors": "prior streptococcal pharyngitis or skin infection (1-3 weeks prior), other infections",
        "demographics": "children 5-15 (post-strep), males 2:1",
        "red_flags": "severe hypertension, pulmonary edema, acute kidney injury, nephrotic-range proteinuria",
        "urgency": "urgent",
        "description": "Inflammation of the glomeruli following infection, most commonly post-streptococcal. Usually self-limiting in children but can progress in adults.",
    },
    {
        "id": "neph_005", "name": "Lupus Nephritis", "icd10": "M32.1",
        "symptoms": "edema, hematuria, proteinuria, hypertension, fatigue, joint pain, rash, fever, foamy urine, weight gain",
        "specialties": "Nephrology, Rheumatology",
        "prevalence": "common in SLE", "risk_factors": "systemic lupus erythematosus, female sex, African American, Hispanic, young adults",
        "demographics": "females 15-45, higher severity in African Americans and Hispanics",
        "red_flags": "rapidly progressive GN, nephrotic syndrome, renal failure, Class IV diffuse proliferative (worst prognosis)",
        "urgency": "urgent",
        "description": "Kidney inflammation caused by systemic lupus erythematosus. Ranges from mild mesangial to full-house proliferative. Renal biopsy required for classification.",
    },
    {
        "id": "neph_006", "name": "Kidney Stones (Urolithiasis)", "icd10": "N20",
        "symptoms": "severe flank pain (renal colic), hematuria, nausea, vomiting, restlessness, urinary frequency, dysuria, fever (if infected stone)",
        "specialties": "Urology, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "dehydration, high-protein diet, hypercalciuria, hyperuricosuria, family history, obesity, recurrent UTIs",
        "demographics": "males 30-60, females slightly less",
        "red_flags": "infected stone (fever + obstruction = urosepsis), solitary kidney obstruction, bilateral obstruction, renal failure",
        "urgency": "urgent",
        "description": "Crystalline deposits in the urinary tract. Most common: calcium oxalate/phosphate. Colic pain is one of the most severe pains known.",
    },
    {
        "id": "neph_007", "name": "Urinary Tract Infection (Pyelonephritis)", "icd10": "N10",
        "symptoms": "fever, flank pain, nausea, vomiting, dysuria, frequency, urgency, costovertebral angle tenderness, pyuria, bacteriuria",
        "specialties": "Urology, Nephrology, Internal Medicine",
        "prevalence": "very common", "risk_factors": "female sex, sexual activity, urinary obstruction, catheter, diabetes, immunosuppression, vesicoureteral reflux",
        "demographics": "females more than males, young sexually active women",
        "red_flags": "urosepsis (hypotension, altered mental status), emphysematous pyelonephritis, renal/perinephric abscess",
        "urgency": "urgent",
        "description": "Infection of the kidney parenchyma and renal pelvis. Usually ascending from lower UTI. E. coli is the most common pathogen.",
    },
    {
        "id": "neph_008", "name": "Urinary Obstruction (Hydronephrosis)", "icd10": "N13",
        "symptoms": "flank pain, palpable renal mass (in chronic cases), anuria or oliguria, recurrent UTIs, hematuria, renal failure",
        "specialties": "Urology, Nephrology",
        "prevalence": "moderate", "risk_factors": "kidney stones, benign prostatic hyperplasia, tumors, strictures, retroperitoneal fibrosis, pregnancy",
        "demographics": "depends on cause, elderly males (BPH), kidney stones (young adults)",
        "red_flags": "bilateral obstruction (anuria, renal failure), infected hydronephrosis (fever + obstruction = emergency)",
        "urgency": "emergency (if infected or bilateral)",
        "description": "Swelling of the kidney from urine backup due to obstruction. Can be unilateral or bilateral. Infected obstruction is a urological emergency.",
    },
    {
        "id": "neph_009", "name": "Polycystic Kidney Disease", "icd10": "Q61.3",
        "symptoms": "bilateral flank mass, flank pain, hematuria, hypertension, recurrent UTIs, kidney stones, headache (berry aneurysm)",
        "specialties": "Nephrology, Genetics",
        "prevalence": "common genetic kidney disease", "risk_factors": "autosomal dominant (PKD1 on chr 16, PKD2 on chr 4), family history",
        "demographics": "symptoms typically 30-50, leads to ESRD by 60",
        "red_flags": "intracranial aneurysm rupture, renal failure, liver cysts, cardiac valvular disease",
        "urgency": "urgent",
        "description": "Inherited disorder with progressive growth of renal cysts leading to kidney enlargement and failure. PKD1 more severe than PKD2.",
    },
    {
        "id": "neph_010", "name": "Hemolytic Uremic Syndrome", "icd10": "D59.3",
        "symptoms": "microangiopathic hemolytic anemia, thrombocytopenia, acute kidney injury, diarrhea (often bloody), abdominal pain, petechiae, pallor, fatigue",
        "specialties": "Nephrology, Hematology, Infectious Disease",
        "prevalence": "uncommon", "risk_factors": "Shiga toxin-producing E. coli (STEC O157:H7), most common in children, complement dysregulation (atypical)",
        "demographics": "children under 5 (typical HUS), adults (atypical HUS)",
        "red_flags": "severe AKI requiring dialysis, seizures, pancreatitis, stroke, DIC",
        "urgency": "emergency",
        "description": "Triad of microangiopathic hemolytic anemia, thrombocytopenia, and acute kidney injury. Typical HUS follows STEC infection.",
    },
    {
        "id": "neph_011", "name": "Renal Tubular Acidosis", "icd10": "N25.8",
        "symptoms": "metabolic acidosis with normal anion gap, hypokalemia (type 1 and 2), nephrocalcinosis (type 1), kidney stones, growth retardation (children), muscle weakness",
        "specialties": "Nephrology",
        "prevalence": "uncommon", "risk_factors": "autoimmune disease (Sjögren, SLE), medications (lithium, amphotericin), hereditary, sickle cell disease",
        "demographics": "depends on cause",
        "red_flags": "severe metabolic acidosis, nephrocalcinosis with renal failure, growth failure in children",
        "urgency": "urgent",
        "description": "Group of disorders affecting renal acid-base regulation. Classified by the site of tubular defect (proximal vs distal).",
    },
]
