"""Neurological system diagnoses (ICD-10 chapter VI)."""

NEUROLOGY_DIAGNOSES: list[dict] = [
    {
        "id": "neuro_001", "name": "Ischemic Stroke", "icd10": "I63",
        "symptoms": "sudden weakness on one side, facial droop, slurred speech, difficulty speaking, vision loss, dizziness, confusion, numbness, trouble walking, trouble understanding speech",
        "specialties": "Neurology, Emergency Medicine",
        "prevalence": "common", "risk_factors": "atrial fibrillation, hypertension, diabetes, smoking, carotid stenosis, heart failure, prior TIA",
        "demographics": "adults over 60, males higher risk, African Americans higher risk",
        "red_flags": "acute onset focal deficit, NIHSS >4, large vessel occlusion, hemorrhagic transformation risk",
        "urgency": "emergency",
        "description": "Brain tissue death from blocked blood supply. Time-sensitive: thrombolysis within 4.5 hours, thrombectomy within 24 hours for large vessel occlusion.",
    },
    {
        "id": "neuro_002", "name": "Hemorrhagic Stroke (Intracerebral)", "icd10": "I61",
        "symptoms": "sudden severe headache, vomiting, altered consciousness, weakness on one side, speech difficulty, seizures, neck stiffness, hypertension",
        "specialties": "Neurology, Neurosurgery, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "hypertension, cerebral amyloid angiopathy, anticoagulant use, AVM, aneurysm, cavernous malformation",
        "demographics": "elderly over 65, hypertensive patients, Asian populations",
        "red_flags": "rapid neurological deterioration, rising ICP, herniation, hydrocephalus",
        "urgency": "emergency",
        "description": "Bleeding into brain parenchyma. Hypertensive hemorrhage most common in basal ganglia, thalamus, pons, and cerebellum. High mortality.",
    },
    {
        "id": "neuro_003", "name": "Subarachnoid Hemorrhage", "icd10": "I60",
        "symptoms": "thunderclap headache (worst headache of life), neck stiffness, vomiting, photophobia, loss of consciousness, seizures, focal deficits, nausea",
        "specialties": "Neurology, Neurosurgery, Emergency Medicine",
        "prevalence": "uncommon", "risk_factors": "berry aneurysm rupture, AVM, smoking, hypertension, alcohol use, family history of aneurysms",
        "demographics": "40-60 years, females slightly more than males",
        "red_flags": "thunderclap headache, rapid deterioration, rebleeding risk, vasospasm (days 3-14)",
        "urgency": "emergency",
        "description": "Bleeding into the subarachnoid space, usually from ruptured cerebral aneurysm. Extremely dangerous with high mortality and rebleeding risk.",
    },
    {
        "id": "neuro_004", "name": "Transient Ischemic Attack (TIA)", "icd10": "G45.9",
        "symptoms": "temporary weakness, temporary numbness, slurred speech, vision loss, dizziness, confusion, symptoms resolve within minutes to hours",
        "specialties": "Neurology, Emergency Medicine",
        "prevalence": "common", "risk_factors": "carotid stenosis, atrial fibrillation, hypertension, diabetes, smoking",
        "demographics": "adults over 55, higher in males",
        "red_flags": "ABCD2 score >=4 (high stroke risk), multiple TIAs, crescendo TIAs",
        "urgency": "emergency",
        "description": "Brief episode of neurological dysfunction from focal brain ischemia without infarction. A major warning sign for impending stroke.",
    },
    {
        "id": "neuro_005", "name": "Epilepsy / Seizure Disorder", "icd10": "G40",
        "symptoms": "recurrent seizures, tonic-clonic movements, staring spells, loss of consciousness, confusion after episode, tongue biting, urinary incontinence, automatisms",
        "specialties": "Neurology, Epileptology",
        "prevalence": "common", "risk_factors": "head injury, stroke, brain tumor, infection, genetic, febrile seizures in childhood",
        "demographics": "bimodal: children under 10 and adults over 65",
        "red_flags": "status epilepticus (>5 minutes), first seizure, cluster seizures, seizure with fever (infection), new-onset in elderly (tumor)",
        "urgency": "urgent",
        "description": "Recurrent unprovoked seizures from excessive neuronal discharge. Classified by seizure type and epilepsy syndrome.",
    },
    {
        "id": "neuro_006", "name": "Status Epilepticus", "icd10": "G41",
        "symptoms": "prolonged seizure lasting more than 5 minutes, continuous seizure activity, recurrent seizures without consciousness, altered mental status, cyanosis",
        "specialties": "Emergency Medicine, Neurology",
        "prevalence": "uncommon", "risk_factors": "uncontrolled epilepsy, medication non-compliance, alcohol withdrawal, metabolic derangements, CNS infection",
        "demographics": "any age, higher in young children and elderly",
        "red_flags": "seizure >5 minutes, convulsive status epilepticus, respiratory compromise, hyperthermia",
        "urgency": "emergency",
        "description": "Prolonged or recurrent seizures without recovery between episodes. A neurological emergency requiring immediate benzodiazepine administration.",
    },
    {
        "id": "neuro_007", "name": "Migraine", "icd10": "G43",
        "symptoms": "throbbing headache, unilateral headache, photophobia, phonophobia, nausea, vomiting, aura (visual disturbance), sensitivity to light and smell, neck pain",
        "specialties": "Neurology",
        "prevalence": "very common", "risk_factors": "female sex, family history, hormonal changes, stress, certain foods, sleep changes, weather changes",
        "demographics": "females 18-45 (3:1 female to male ratio)",
        "red_flags": "first severe headache, sudden onset, fever, stiff neck, visual loss, worst headache of life, new neurological deficit",
        "urgency": "routine",
        "description": "Recurrent episodic headache with characteristic pulsating quality, unilateral location, and associated nausea/photophobia. Can be debilitating.",
    },
    {
        "id": "neuro_008", "name": "Multiple Sclerosis", "icd10": "G35",
        "symptoms": "numbness, tingling, vision loss (optic neuritis), double vision, weakness, balance problems, fatigue, bladder dysfunction, cognitive difficulties, Lhermitte sign",
        "specialties": "Neurology",
        "prevalence": "moderate", "risk_factors": "female sex, northern latitude, vitamin D deficiency, EBV infection, family history",
        "demographics": "females 20-40, female to male ratio 3:1",
        "red_flags": "severe relapse with significant disability, brainstem involvement, respiratory weakness",
        "urgency": "urgent",
        "description": "Autoimmune demyelinating disease of the CNS with relapsing-remitting or progressive course. Characterized by dissemination in time and space.",
    },
    {
        "id": "neuro_009", "name": "Parkinson's Disease", "icd10": "G20",
        "symptoms": "tremor at rest, bradykinesia, rigidity, postural instability, shuffling gait, mask-like face, monotone voice, constipation, depression, sleep disturbance, micrographia",
        "specialties": "Neurology, Movement Disorders",
        "prevalence": "common in elderly", "risk_factors": "age, male sex, pesticide exposure, head trauma, family history",
        "demographics": "males over 60, increases with age",
        "red_flags": "falls, dysphagia, dementia, autonomic dysfunction, psychosis",
        "urgency": "routine",
        "description": "Progressive neurodegenerative disorder affecting dopaminergic neurons in substantia nigra. Cardinal features: rest tremor, bradykinesia, rigidity, postural instability.",
    },
    {
        "id": "neuro_010", "name": "Bell's Palsy", "icd10": "G51.0",
        "symptoms": "sudden facial weakness, facial droop, inability to close eye, drooling, loss of taste, ear pain, hypersensitivity to sound, dry eye",
        "specialties": "Neurology, ENT",
        "prevalence": "common", "risk_factors": "HSV-1 reactivation, diabetes, pregnancy, upper respiratory infection, immunosuppression",
        "demographics": "any age, peaks 15-45, slight female predominance",
        "red_flags": "incomplete recovery, bilateral facial palsy (suggests Lyme disease or GBS), recurrence (tumor)",
        "urgency": "urgent",
        "description": "Acute idiopathic lower motor neuron facial paralysis. Usually unilateral and self-limiting. Early corticosteroids improve outcomes.",
    },
    {
        "id": "neuro_011", "name": "Guillain-Barré Syndrome", "icd10": "G61.0",
        "symptoms": "ascending weakness, areflexia, tingling in extremities, difficulty walking, difficulty breathing, facial weakness, autonomic dysfunction, pain",
        "specialties": "Neurology, Critical Care",
        "prevalence": "uncommon", "risk_factors": "recent infection (Campylobacter, CMV, EBV, Zika), vaccination (rare), surgery",
        "demographics": "any age, slight male predominance",
        "red_flags": "respiratory failure requiring ventilator, autonomic instability, bulbar weakness",
        "urgency": "emergency",
        "description": "Acute immune-mediated polyradiculoneuropathy causing ascending paralysis. Most common cause of acute flaccid paralysis worldwide.",
    },
    {
        "id": "neuro_012", "name": "Myasthenia Gravis", "icd10": "G70.0",
        "symptoms": "fatigable weakness, ptosis, double vision, difficulty swallowing, difficulty speaking, weakness worse with activity, limb weakness, respiratory difficulty",
        "specialties": "Neurology",
        "prevalence": "uncommon", "risk_factors": "thymoma, autoimmune disease, female sex (young), male sex (old)",
        "demographics": "bimodal: females 20-30, males 50-70",
        "red_flags": "myasthenic crisis (respiratory failure), aspiration risk, bulbar weakness",
        "urgency": "urgent",
        "description": "Autoimmune disorder causing fatigable weakness due to antibodies against acetylcholine receptors at the neuromuscular junction.",
    },
    {
        "id": "neuro_013", "name": "Trigeminal Neuralgia", "icd10": "G50.0",
        "symptoms": "severe facial pain, electric shock-like pain, pain triggered by touch, chewing, talking, brushing teeth, pain in distribution of trigeminal nerve (V2, V3)",
        "specialties": "Neurology, Neurosurgery",
        "prevalence": "uncommon", "risk_factors": "multiple sclerosis, vascular compression of trigeminal nerve, age over 50",
        "demographics": "females over 50, MS patients at younger age",
        "red_flags": "bilateral involvement (suggests MS), numbness (atypical), constant pain",
        "urgency": "routine",
        "description": "Episodic severe facial pain in the trigeminal nerve distribution, triggered by light touch. One of the most painful conditions known.",
    },
    {
        "id": "neuro_014", "name": "Meningitis (Bacterial)", "icd10": "G00",
        "symptoms": "fever, severe headache, neck stiffness (nuchal rigidity), photophobia, vomiting, altered mental status, seizures, petechial rash (meningococcal)",
        "specialties": "Infectious Disease, Neurology, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "immunosplenism, complement deficiency, CSF leak, cochlear implants, college dormitory living",
        "demographics": "bimodal: infants <1 and young adults 16-23, elderly",
        "red_flags": "altered consciousness, seizures, focal deficits, petechial rash, raised ICP",
        "urgency": "emergency",
        "description": "Infection of the meninges surrounding the brain and spinal cord. Bacterial meningitis is a medical emergency requiring immediate antibiotics.",
    },
    {
        "id": "neuro_015", "name": "Encephalitis", "icd10": "A86",
        "symptoms": "fever, headache, altered mental status, seizures, personality changes, memory loss, focal neurological deficits, behavioral changes, speech difficulties",
        "specialties": "Neurology, Infectious Disease",
        "prevalence": "uncommon", "risk_factors": "HSV-1 infection, arboviral infection (West Nile, Japanese encephalitis), autoimmune, immunosuppression",
        "demographics": "any age, HSV encephalitis all ages, arboviral depends on geography",
        "red_flags": "rapidly progressive encephalopathy, status epilepticus, herniation, temporal lobe involvement (HSV)",
        "urgency": "emergency",
        "description": "Inflammation of brain parenchyma, most commonly viral (HSV-1). Medical emergency requiring empiric acyclovir pending workup.",
    },
    {
        "id": "neuro_016", "name": "Brain Tumor (Glioblastoma)", "icd10": "C71",
        "symptoms": "progressive headache, seizures, cognitive decline, personality changes, focal weakness, speech difficulty, vision changes, nausea, vomiting, hemiparesis",
        "specialties": "Neurology, Neurosurgery, Oncology",
        "prevalence": "uncommon", "risk_factors": "age over 50, ionizing radiation exposure, genetic syndromes (NF1, Li-Fraumeni)",
        "demographics": "males over 50, peak incidence 55-65",
        "red_flags": "rapidly progressive symptoms, new-onset seizures in elderly, papilledema, declining consciousness",
        "urgency": "urgent",
        "description": "Most common and aggressive primary brain tumor. WHO grade IV astrocytoma with median survival of 15 months despite treatment.",
    },
    {
        "id": "neuro_017", "name": "Subdural Hematoma (Acute)", "icd10": "I62.0",
        "symptoms": "headache, confusion, decreasing consciousness, seizures, hemiparesis, nausea, vomiting, drowsiness, slurred speech",
        "specialties": "Neurosurgery, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "head trauma, elderly (brain atrophy), anticoagulant use, alcoholism, chronic liver disease",
        "demographics": "elderly over 65, infants (non-accidental injury), alcoholics",
        "red_flags": "rapid neurological deterioration, pupillary asymmetry, decerebrate posturing, herniation",
        "urgency": "emergency",
        "description": "Bleeding between dura and arachnoid mater, usually from bridging vein rupture. Acute form is a neurosurgical emergency.",
    },
    {
        "id": "neuro_018", "name": "Epidural Hematoma", "icd10": "I62.1",
        "symptoms": "head injury, brief loss of consciousness, lucid interval, rapid deterioration, severe headache, vomiting, seizures, pupil dilation (ipsilateral)",
        "specialties": "Neurosurgery, Emergency Medicine",
        "prevalence": "uncommon", "risk_factors": "temporal bone fracture, middle meningeal artery rupture, young adults (skull more elastic)",
        "demographics": "young adults 20-30, males (trauma more common)",
        "red_flags": "lucid interval followed by rapid deterioration, uncal herniation, fixed dilated pupil",
        "urgency": "emergency",
        "description": "Bleeding between skull and dura mater, typically from middle meningeal artery rupture. Classic presentation: head trauma → lucid interval → rapid decline.",
    },
    {
        "id": "neuro_019", "name": "Vertebral Compression Fracture", "icd10": "S22.0",
        "symptoms": "sudden back pain, loss of height, kyphosis, limited spinal mobility, pain with standing/walking, tenderness over spine",
        "specialties": "Orthopedics, Neurology, Endocrinology",
        "prevalence": "common", "risk_factors": "osteoporosis, cancer metastasis, steroid use, aging, trauma, low BMI",
        "demographics": "postmenopausal women, elderly over 70",
        "red_flags": "neurological deficit (cauda equina), progressive deformity, pain at rest",
        "urgency": "urgent",
        "description": "Fracture of a vertebral body, most commonly in the thoracolumbar junction. Can be osteoporotic or pathologic.",
    },
    {
        "id": "neuro_020", "name": "Cervical Spondylotic Myelopathy", "icd10": "M47.1",
        "symptoms": "hand clumsiness, gait instability, neck pain, arm numbness, weakness in legs, hyperreflexia, Babinski sign, Lhermitte sign",
        "specialties": "Neurosurgery, Orthopedics, Neurology",
        "prevalence": "common", "risk_factors": "aging, cervical spine degeneration, congenital stenosis, trauma",
        "demographics": "adults over 50, males more than females",
        "red_flags": "acute worsening, bowel/bladder dysfunction, rapid progression",
        "urgency": "urgent",
        "description": "Compression of the cervical spinal cord due to degenerative changes. Most common cause of myelopathy in adults over 55.",
    },
    {
        "id": "neuro_021", "name": "Carpal Tunnel Syndrome", "icd10": "G56.0",
        "symptoms": "numbness and tingling in thumb, index, middle fingers, night pain, weakness in grip, dropping objects, pain radiating to forearm",
        "specialties": "Neurology, Orthopedics, Hand Surgery",
        "prevalence": "very common", "risk_factors": "repetitive hand use, pregnancy, hypothyroidism, diabetes, obesity, rheumatoid arthritis",
        "demographics": "females 30-60, dominant hand more affected",
        "red_flags": "thenar atrophy, severe weakness, acute onset after trauma",
        "urgency": "routine",
        "description": "Compression of the median nerve at the wrist. Most common entrapment neuropathy. Characterized by thenar numbness and weakness.",
    },
    {
        "id": "neuro_022", "name": "Restless Legs Syndrome", "icd10": "G25.8",
        "symptoms": "uncomfortable sensation in legs, urge to move legs, worse at rest, worse in evening/night, relieved by movement, sleep disturbance",
        "specialties": "Neurology, Sleep Medicine",
        "prevalence": "common", "risk_factors": "iron deficiency, renal failure, pregnancy, family history, peripheral neuropathy, medications (antihistamines, antidepressants)",
        "demographics": "females 2:1, middle-aged",
        "red_flags": "refractory to treatment, severe sleep disruption, associated with periodic limb movements",
        "urgency": "routine",
        "description": "Neurological disorder with uncomfortable leg sensations and irresistible urge to move. Often disrupts sleep.",
    },
    {
        "id": "neuro_023", "name": "Peripheral Neuropathy (Diabetic)", "icd10": "E11.4",
        "symptoms": "numbness in feet, tingling in feet, burning pain in feet, loss of sensation, foot ulcers, loss of balance, glove-and-stocking distribution",
        "specialties": "Neurology, Endocrinology",
        "prevalence": "very common in diabetics", "risk_factors": "diabetes mellitus, poor glycemic control, long disease duration, alcohol use",
        "demographics": "diabetics over 10 years duration, older adults",
        "red_flags": "foot ulceration, Charcot joint, infection, falls",
        "urgency": "routine",
        "description": "Nerve damage from chronic hyperglycemia, typically causing distal symmetric polyneuropathy in a glove-and-stocking distribution.",
    },
    {
        "id": "neuro_024", "name": "Alzheimer's Disease", "icd10": "G30",
        "symptoms": "progressive memory loss, confusion, difficulty with familiar tasks, word-finding difficulty, disorientation, personality changes, difficulty with abstract thinking, apathy",
        "specialties": "Neurology, Geriatric Medicine, Psychiatry",
        "prevalence": "very common in elderly", "risk_factors": "age over 65, ApoE4 genotype, family history, low education, cardiovascular risk factors, female sex",
        "demographics": "elderly over 65, doubles in prevalence every 5 years after 65",
        "red_flags": "rapid decline, early gait disturbance, early falls, visual hallucinations, parkinsonism (suggests Lewy body)",
        "urgency": "routine",
        "description": "Most common cause of dementia. Progressive neurodegeneration with amyloid plaques and neurofibrillary tangles. Insidious onset with gradual decline.",
    },
    {
        "id": "neuro_025", "name": "Vascular Dementia", "icd10": "F01",
        "symptoms": "stepwise cognitive decline, executive dysfunction, mood changes, slowed thinking, difficulty planning, urinary urgency, gait problems, apathy",
        "specialties": "Neurology, Geriatric Medicine, Psychiatry",
        "prevalence": "common", "risk_factors": "stroke, hypertension, diabetes, atrial fibrillation, cerebral small vessel disease",
        "demographics": "elderly over 65, males slightly more",
        "red_flags": "acute cognitive decline after stroke, stepwise deterioration",
        "urgency": "routine",
        "description": "Dementia caused by cerebrovascular disease. Characterized by stepwise decline, executive dysfunction, and subcortical features.",
    },
]
