"""Oncology diagnoses (ICD-10 chapter II)."""

ONCOLOGY_DIAGNOSES: list[dict] = [
    {
        "id": "onc_001", "name": "Breast Cancer", "icd10": "C50",
        "symptoms": "breast mass, painless lump, skin dimpling, nipple retraction, nipple discharge (bloody), axillary lymphadenopathy, skin changes",
        "specialties": "Oncology, Surgery, Radiology",
        "prevalence": "very common", "risk_factors": "female sex, age, BRCA1/2 mutations, family history, early menarche, late menopause, obesity, alcohol, HRT",
        "demographics": "females, peak 55-65, males rare (<1%)",
        "red_flags": "inflammatory breast cancer (peau d'orange), Paget disease, metastatic disease (bone pain, liver, lung)",
        "urgency": "urgent",
        "description": "Most common cancer in females worldwide. Detected by mammography, ultrasound, and biopsy. Treatment: surgery, radiation, chemotherapy, hormonal therapy, targeted therapy.",
    },
    {
        "id": "onc_002", "name": "Lung Cancer (Small Cell)", "icd10": "C34",
        "symptoms": "persistent cough, hemoptysis, weight loss, chest pain, shortness of breath, hoarseness, superior vena cava syndrome, Cushing syndrome (ectopic ACTH)",
        "specialties": "Oncology, Pulmonology",
        "prevalence": "common", "risk_factors": "smoking (strongest risk factor, >95%), radon, asbestos, prior radiation",
        "demographics": "males > females, median age 70",
        "red_flags": "SVC syndrome, SIADH, Cushing syndrome, brain metastases, rapid growth",
        "urgency": "urgent",
        "description": "Aggressive neuroendocrine tumor strongly linked to smoking. Rapid growth, early metastasis. Chemosensitive initially but poor long-term survival.",
    },
    {
        "id": "onc_003", "name": "Colorectal Cancer", "icd10": "C18-C20",
        "symptoms": "change in bowel habits, rectal bleeding, blood in stool, abdominal pain, weight loss, iron deficiency anemia, tenesmus, obstruction",
        "specialties": "Oncology, Gastroenterology, Colorectal Surgery",
        "prevalence": "common", "risk_factors": "age >50, polyps, IBD, Lynch syndrome, FAP, low-fiber diet, obesity, smoking, red meat",
        "demographics": "adults >50, increasing in younger adults",
        "red_flags": "obstruction, perforation, liver metastases, peritoneal carcinomatosis",
        "urgency": "urgent",
        "description": "Third most common cancer worldwide. Develops from adenomatous polyps over 10-15 years. Screening colonoscopy is key to prevention and early detection.",
    },
    {
        "id": "onc_004", "name": "Prostate Cancer", "icd10": "C61",
        "symptoms": "elevated PSA, difficulty urinating, weak urine stream, hematuria, bone pain (metastatic), weight loss, fatigue",
        "specialties": "Oncology, Urology",
        "prevalence": "very common in elderly males", "risk_factors": "age over 50, family history, African American descent, high-fat diet",
        "demographics": "males over 50, increases with age",
        "red_flags": "metastatic disease (bone pain, fractures, spinal cord compression), castrate-resistant prostate cancer",
        "urgency": "routine",
        "description": "Most common non-skin cancer in males. Many are indolent and don't need treatment. Aggressive forms require surgery, radiation, or hormone therapy.",
    },
    {
        "id": "onc_005", "name": "Gastric Cancer", "icd10": "C16",
        "symptoms": "early satiety, weight loss, abdominal pain, nausea, vomiting, dysphagia, anemia, abdominal mass, ascites",
        "specialties": "Oncology, Gastroenterology, Surgery",
        "prevalence": "common worldwide", "risk_factors": "H. pylori infection, diet (salted/smoked foods), smoking, family history, atrophic gastritis, pernicious anemia",
        "demographics": "males > females, higher in East Asia, age >50",
        "red_flags": "obstruction, bleeding, peritoneal carcinomatosis, Virchow node (left supraclavian)",
        "urgency": "urgent",
        "description": "Fifth most common cancer worldwide. Highly prevalent in East Asia. Often diagnosed at advanced stage. H. pylori is a major risk factor.",
    },
    {
        "id": "onc_006", "name": "Pancreatic Cancer", "icd10": "C25",
        "symptoms": "painless jaundice, weight loss, abdominal pain (radiating to back), new-onset diabetes, nausea, steatorrhea, depression, anorexia",
        "specialties": "Oncology, Gastroenterology, Hepatology, Surgery",
        "prevalence": "moderate", "risk_factors": "smoking, obesity, chronic pancreatitis, diabetes, family history, BRCA2, Lynch syndrome",
        "demographics": "males > females, peak 65-80",
        "red_flags": "obstructive jaundice, cachexia, thrombophlebitis (Trousseau syndrome), new-onset diabetes >50",
        "urgency": "urgent",
        "description": "One of the deadliest cancers with 5-year survival <12%. Often diagnosed at advanced stage. Painless jaundice may be the only early sign.",
    },
    {
        "id": "onc_007", "name": "Hepatocellular Carcinoma", "icd10": "C22.0",
        "symptoms": "right upper quadrant pain, weight loss, hepatomegaly, jaundice, ascites, hepatomegaly in cirrhotic patient, elevated AFP",
        "specialties": "Oncology, Hepatology",
        "prevalence": "common worldwide", "risk_factors": "cirrhosis (any cause), chronic hepatitis B/C, aflatoxin, alcohol, NAFLD/NASH, hemochromatosis",
        "demographics": "males 2-3:1, age depends on underlying disease",
        "red_flags": "tumor rupture/bleeding, portal vein thrombosis, hepatic decompensation, metastatic disease",
        "urgency": "urgent",
        "description": "Primary liver cancer, most commonly arising in the setting of cirrhosis. Hepatitis B and C are the most common causes worldwide.",
    },
    {
        "id": "onc_008", "name": "Thyroid Cancer", "icd10": "C73",
        "symptoms": "thyroid nodule, neck mass, dysphagia, hoarseness, enlarged cervical lymph nodes, neck pain",
        "specialties": "Oncology, Endocrinology, Surgery",
        "prevalence": "common (most common endocrine malignancy)", "risk_factors": "radiation exposure, family history, MEN syndromes, iodine deficiency (follicular), female sex",
        "demographics": "females 3:1, ages 25-65, peak 45-50",
        "red_flags": "recurrent laryngeal nerve invasion (hoarseness), distant metastases (lung, bone), anaplastic thyroid cancer (aggressive)",
        "urgency": "routine",
        "description": "Most common endocrine malignancy. Papillary most common (excellent prognosis). Anaplastic is rare but extremely aggressive.",
    },
    {
        "id": "onc_009", "name": "Cervical Cancer", "icd10": "C53",
        "symptoms": "vaginal bleeding (intercoital, postmenopausal), abnormal discharge, pelvic pain, dyspareunia, back pain",
        "specialties": "Oncology, Gynecologic Oncology",
        "prevalence": "common worldwide", "risk_factors": "HPV infection (types 16, 18), multiple sexual partners, early sexual activity, smoking, immunosuppression",
        "demographics": "females 30-50, highest incidence in developing countries",
        "red_flags": "hydronephrosis (ureteral obstruction), deep pelvic invasion, metastatic disease",
        "urgency": "urgent",
        "description": "Almost always caused by high-risk HPV. Preventable by HPV vaccine and screening (Pap smear). Detected at earlier stage in screened populations.",
    },
    {
        "id": "onc_010", "name": "Leukemia (Acute Lymphoblastic)", "icd10": "C91.0",
        "symptoms": "fatigue, pallor, fever, infections, bleeding (petechiae, bruising), bone pain, lymphadenopathy, hepatosplenomegaly, weight loss",
        "specialties": "Oncology, Hematology",
        "prevalence": "most common childhood cancer", "risk_factors": "Down syndrome, genetic syndromes, prior chemotherapy/radiation, family history",
        "demographics": "peak 2-5 years, slight male predominance, 85% cure rate in children",
        "red_flags": "tumor lysis syndrome, sepsis, severe bleeding, CNS involvement",
        "urgency": "urgent",
        "description": "Most common cancer in children. Malignant proliferation of lymphoid progenitor cells. Excellent prognosis in children (>90% cure).",
    },
    {
        "id": "onc_011", "name": "Lymphoma (Diffuse Large B-Cell)", "icd10": "C83.3",
        "symptoms": "rapidly enlarging lymph node, B symptoms (fever, night sweats, >10% weight loss), fatigue, pruritus, hepatosplenomegaly",
        "specialties": "Oncology, Hematology",
        "prevalence": "most common NHL subtype", "risk_factors": "immunosuppression (HIV, transplant), autoimmune disease, H. pylori (MALT lymphoma), EBV",
        "demographics": "adults median age 60-65, slight male predominance",
        "red_flags": "mediastinal mass (airway compromise), superior vena cava syndrome, tumor lysis syndrome",
        "urgency": "urgent",
        "description": "Most common non-Hodgkin lymphoma subtype. Aggressive but potentially curable with R-CHOP chemotherapy.",
    },
    {
        "id": "onc_012", "name": "Melanoma", "icd10": "C43",
        "symptoms": "changing mole, asymmetric lesion, irregular borders, multiple colors, diameter >6mm, evolving, bleeding, itching",
        "specialties": "Oncology, Dermatology, Surgery",
        "prevalence": "common", "risk_factors": "UV exposure, fair skin, sunburns, family history, atypical nevi, immunosuppression",
        "demographics": "young adults (25-29), increasing with age, Caucasians",
        "red_flags": "ulceration, high Breslow thickness, lymph node metastases, distant metastases (lung, brain, liver)",
        "urgency": "urgent",
        "description": "Most deadly skin cancer. Detected early: >99% 5-year survival. Metastatic: <30% survival. ABCDE criteria for screening.",
    },
    {
        "id": "onc_013", "name": "Multiple Myeloma", "icd10": "C90.0",
        "symptoms": "bone pain (back, ribs), anemia, fatigue, recurrent infections, renal failure, hypercalcemia, weight loss, peripheral neuropathy",
        "specialties": "Oncology, Hematology",
        "prevalence": "moderate", "risk_factors": "age, obesity, family history, monoclonal gammopathy of undetermined significance (MGUS)",
        "demographics": "median age 65-70, males > females, African Americans 2x risk",
        "red_flags": "spinal cord compression, hypercalcemic crisis, renal failure, severe infections",
        "urgency": "urgent",
        "description": "Plasma cell malignancy with CRAB criteria: Calcium elevation, Renal insufficiency, Anemia, Bone lesions. Incurable but treatable.",
    },
    {
        "id": "onc_014", "name": "Brain Metastases", "icd10": "C79.3",
        "symptoms": "headache (worse in morning), seizures, focal neurological deficits, cognitive changes, personality changes, nausea, vomiting, papilledema",
        "specialties": "Oncology, Neurology, Neurosurgery, Radiation Oncology",
        "prevalence": "common", "risk_factors": "known primary cancer (lung, breast, melanoma, renal, colon), multiple primary sites",
        "demographics": "adults with known malignancy, median age 60",
        "red_flags": "raised ICP, herniation, seizures, neurological emergency",
        "urgency": "urgent",
        "description": "Secondary tumors in the brain from metastatic cancer. Most common primaries: lung, breast, melanoma, renal, colon. Can present before primary diagnosis.",
    },
    {
        "id": "onc_015", "name": "Bone Metastases", "icd10": "C79.5",
        "symptoms": "bone pain, pathological fractures, spinal cord compression, hypercalcemia, alkaline phosphatase elevation, weight loss",
        "specialties": "Oncology, Orthopedics, Radiation Oncology",
        "prevalence": "common in advanced cancer", "risk_factors": "breast, prostate, lung, renal, thyroid cancers (most likely to metastasize to bone)",
        "demographics": "adults with advanced malignancy",
        "red_flags": "spinal cord compression (emergency), pathological fracture, severe hypercalcemia",
        "urgency": "urgent",
        "description": "Cancer that has spread to bone from a primary tumor. Prostate and breast cancer most commonly metastasize to bone.",
    },
]
