"""Rheumatology, Hematology, Dermatology, Orthopedics, OB/GYN, Pediatrics, ENT, and other system diagnoses."""

OTHER_DIAGNOSES: list[dict] = [
    # ── Rheumatology ──
    {
        "id": "rheum_001", "name": "Rheumatoid Arthritis", "icd10": "M06",
        "symptoms": "symmetric joint swelling, morning stiffness >30 minutes, small joint involvement (MCP, PIP, wrists), fatigue, rheumatoid nodules, joint deformity",
        "specialties": "Rheumatology",
        "prevalence": "common (1%)", "risk_factors": "female sex, smoking, family history, HLA-DR4, silica exposure",
        "demographics": "females 3:1, peak onset 30-60",
        "red_flags": "atlantoaxial subluxation, vasculitis, interstitial lung disease, Felty syndrome",
        "urgency": "urgent",
        "description": "Chronic autoimmune inflammatory arthritis causing symmetric joint destruction. Early treatment with DMARDs is crucial to prevent irreversible damage.",
    },
    {
        "id": "rheum_002", "name": "Systemic Lupus Erythematosus", "icd10": "M32",
        "symptoms": "malar (butterfly) rash, photosensitivity, oral ulcers, arthritis, serositis (pleuritis, pericarditis), renal involvement, fatigue, Raynaud phenomenon",
        "specialties": "Rheumatology",
        "prevalence": "moderate", "risk_factors": "female sex, African American/Hispanic, family history, sunlight exposure, estrogen",
        "demographics": "females 9:1, peak 15-45, higher severity in African Americans",
        "red_flags": "lupus nephritis, CNS lupus, antiphospholipid syndrome, thrombocytopenia, serositis",
        "urgency": "urgent",
        "description": "Systemic autoimmune disease with multi-organ involvement. Characterized by autoantibodies (ANA, anti-dsDNA). Can affect any organ system.",
    },
    {
        "id": "rheum_003", "name": "Gout", "icd10": "M10",
        "symptoms": "acute severe joint pain (podagra - 1st MTP), redness, swelling, warmth, tenderness, elevated uric acid, tophaceous deposits (chronic)",
        "specialties": "Rheumatology, Internal Medicine",
        "prevalence": "very common", "risk_factors": "male sex, obesity, alcohol (beer), purine-rich foods, diuretics, chronic kidney disease, metabolic syndrome",
        "demographics": "males 30-60, post-menopausal females",
        "red_flags": "renal stones (uric acid), tophaceous gout, joint destruction, septic arthritis (must rule out)",
        "urgency": "urgent",
        "description": "Inflammatory arthritis caused by monosodium urate crystal deposition from hyperuricemia. Acute attacks are intensely painful but self-limiting.",
    },
    {
        "id": "rheum_004", "name": "Ankylosing Spondylitis", "icd10": "M45",
        "symptoms": "chronic low back pain (improves with exercise, worse with rest), morning stiffness >30 minutes, limited spinal mobility, enthesitis, anterior uveitis",
        "specialties": "Rheumatology",
        "prevalence": "moderate", "risk_factors": "HLA-B27, male sex, family history, inflammatory bowel disease",
        "demographics": "males 2:1, onset 15-30",
        "red_flags": "atlantoaxial subluxation, aortic regurgitation, restrictive lung disease, spinal fractures",
        "urgency": "routine",
        "description": "Chronic inflammatory spondyloarthropathy primarily affecting the axial skeleton. HLA-B27 associated. Leads to bamboo spine if untreated.",
    },
    {
        "id": "rheum_005", "name": "Polymyalgia Rheumatica", "icd10": "M35.3",
        "symptoms": "bilateral shoulder and hip girdle pain and stiffness, morning stiffness >45 minutes, fatigue, weight loss, low-grade fever, elevated ESR/CRP",
        "specialties": "Rheumatology, Internal Medicine",
        "prevalence": "common in elderly", "risk_factors": "age >50, female sex, Scandinavian descent",
        "demographics": "females 2:1, median age 70-75",
        "red_flags": "overlap with giant cell arteritis (15-20%), vision loss (GCA), headache (GCA), jaw claudication",
        "urgency": "urgent",
        "description": "Inflammatory condition causing proximal muscle pain and stiffness in elderly. Rapid response to low-dose prednisone is diagnostic.",
    },
    {
        "id": "rheum_006", "name": "Giant Cell Arteritis", "icd10": "M31.5",
        "symptoms": "new-onset headache, temporal artery tenderness, jaw claudication, visual disturbances, scalp tenderness, polymyalgia rheumatica symptoms, fatigue, weight loss",
        "specialties": "Rheumatology, Ophthalmology",
        "prevalence": "moderate in elderly", "risk_factors": "age >50, female sex, Scandinavian descent, PMR association",
        "demographics": "females 2:1, age >70",
        "red_flags": "anterior ischemic optic neuropathy (permanent blindness), stroke, aortic aneurysm/dissection",
        "urgency": "emergency",
        "description": "Large vessel vasculitis affecting temporal and other cranial arteries. Vision loss is the most feared complication. Treat empirically with steroids if suspected.",
    },
    # ── Hematology ──
    {
        "id": "heme_001", "name": "Iron Deficiency Anemia", "icd10": "D50",
        "symptoms": "fatigue, pallor, dyspnea on exertion, tachycardia, dizziness, pica, koilonychia, angular cheilitis, restless legs, poor concentration",
        "specialties": "Hematology, Internal Medicine, Gastroenterology",
        "prevalence": "very common (most common anemia worldwide)", "risk_factors": "menstruation, pregnancy, poor diet, GI blood loss (ulcer, cancer, hookworm), malabsorption (celiac)",
        "demographics": "females of reproductive age, children, elderly with GI pathology",
        "red_flags": "occult GI malignancy (especially in males and post-menopausal females), severe anemia (Hgb <6), cardiovascular compromise",
        "urgency": "urgent",
        "description": "Anemia from insufficient iron for hemoglobin synthesis. Most common cause of anemia worldwide. Always investigate the underlying cause.",
    },
    {
        "id": "heme_002", "name": "Sickle Cell Disease", "icd10": "D57",
        "symptoms": "chronic hemolytic anemia, jaundice, pain crises (vaso-occlusive), swelling of hands/feet (dactylitis), acute chest syndrome, stroke, priapism, infections",
        "specialties": "Hematology",
        "prevalence": "common (endemic areas)", "risk_factors": "autosomal recessive (HbSS), sickle cell trait (HbAS), malaria-endemic areas",
        "demographics": "African descent, Mediterranean, Middle Eastern, Indian",
        "red_flags": "acute chest syndrome, stroke, sepsis (asplenia), aplastic crisis (parvovirus B19), priapism, multi-organ failure",
        "urgency": "urgent",
        "description": "Genetic hemoglobin disorder causing sickling of red blood cells. Leads to chronic hemolytic anemia, vaso-occlusive crises, and progressive organ damage.",
    },
    {
        "id": "heme_003", "name": "Vitamin B12 Deficiency", "icd10": "D51",
        "symptoms": "fatigue, weakness, paresthesias, ataxia, cognitive decline, glossitis, macrocytic anemia, subacute combined degeneration of spinal cord, depression",
        "specialties": "Hematology, Neurology",
        "prevalence": "moderate", "risk_factors": "pernicious anemia, vegetarian/vegan, gastrectomy, Crohn's disease, metformin use, PPI use, elderly",
        "demographics": "elderly, strict vegetarians, post-gastrectomy",
        "red_flags": "neurological damage (if untreated), megaloblastic crisis, severe anemia",
        "urgency": "urgent",
        "description": "Deficiency of vitamin B12 causing megaloblastic anemia and potentially irreversible neurological damage. Early treatment prevents permanent deficits.",
    },
    {
        "id": "heme_004", "name": "Von Willebrand Disease", "icd10": "D68.0",
        "symptoms": "mucocutaneous bleeding, epistaxis, menorrhagia, easy bruising, bleeding after dental procedures, post-surgical bleeding, GI bleeding",
        "specialties": "Hematology",
        "prevalence": "very common (most common inherited bleeding disorder)", "risk_factors": "autosomal dominant (Type 1 most common), family history",
        "demographics": "equal sex distribution, often diagnosed in childhood",
        "red_flags": "severe bleeding (Type 3), postpartum hemorrhage, GI bleeding from angiodysplasia",
        "urgency": "urgent",
        "description": "Inherited deficiency or dysfunction of von Willebrand factor, important for platelet adhesion and Factor VIII transport. Most common inherited bleeding disorder.",
    },
    # ── Dermatology ──
    {
        "id": "derm_001", "name": "Psoriasis", "icd10": "L40",
        "symptoms": "well-demarcated erythematous plaques with silvery scales, itch, nail changes (pitting, onycholysis), scalp involvement, joint pain (psoriatic arthritis)",
        "specialties": "Dermatology, Rheumatology",
        "prevalence": "common (2-3%)", "risk_factors": "family history, HLA-Cw6, streptococcal infection (guttate), stress, obesity, smoking, medications (lithium, beta-blockers)",
        "demographics": "bimodal: 20-30 and 50-60, equal sex distribution",
        "red_flags": "erythroderma (>90% BSA), psoriatic arthritis, metabolic syndrome, depression, cardiovascular risk",
        "urgency": "urgent (erythroderma)",
        "description": "Chronic autoimmune skin disease with accelerated epidermal turnover. Plaques are well-demarcated with silvery scales. Strong association with metabolic syndrome and cardiovascular disease.",
    },
    {
        "id": "derm_002", "name": "Eczema (Atopic Dermatitis)", "icd10": "L20",
        "symptoms": "pruritus, xerosis, erythematous patches, vesicles, weeping, crusting, lichenification (chronic), flexural involvement (adults), facial/scalp (infants)",
        "specialties": "Dermatology, Allergy/Immunology",
        "prevalence": "very common (10-20% of children)", "risk_factors": "atopic triad (eczema, asthma, allergic rhinitis), family history, filaggrin mutation, dry climate, irritants",
        "demographics": "onset in 60% before age 1, 90% before age 5, improves in many by adulthood",
        "red_flags": "secondary bacterial infection (impetiginization), eczema herpeticum (HSV), sleep disruption, severe impact on quality of life",
        "urgency": "routine",
        "description": "Chronic relapsing inflammatory skin disease with defective skin barrier. Characterized by intense pruritus and typical morphological features.",
    },
    {
        "id": "derm_003", "name": "Cellulitis / Skin Infection", "icd10": "L03",
        "symptoms": "erythema, warmth, swelling, tenderness, spreading redness, fever, lymphangitis, regional lymphadenopathy, skin breaks (entry point)",
        "specialties": "Dermatology, Emergency Medicine, Infectious Disease",
        "prevalence": "very common", "risk_factors": "skin trauma, tinea pedis, edema, lymphedema, diabetes, IV drug use, obesity, immunosuppression",
        "demographics": "all ages, males more, elderly and diabetic at higher risk",
        "red_flags": "necrotizing fasciitis (pain out of proportion, crepitus), sepsis, abscess, osteomyelitis",
        "urgency": "urgent",
        "description": "Bacterial infection of dermis and subcutaneous tissue. S. aureus and Streptococcus pyogenes are most common pathogens.",
    },
    {
        "id": "derm_004", "name": "Herpes Zoster (Shingles)", "icd10": "B02",
        "symptoms": "painful vesicular rash in dermatomal distribution, burning pain preceding rash, pruritus, fever, malaise, regional lymphadenopathy",
        "specialties": "Dermatology, Infectious Disease",
        "prevalence": "common (1 in 3 lifetime risk)", "risk_factors": "age >50, immunosuppression, prior varicella infection, stress, trauma",
        "demographics": "adults >50, immunocompromised at any age",
        "red_flags": "ophthalmic zoster (V1 - risk of blindness), disseminated zoster (immunocompromised), post-herpetic neuralgia, motor nerve involvement",
        "urgency": "urgent",
        "description": "Reactivation of latent varicella-zoster virus in sensory ganglia. Painful dermatomal vesicular rash. Treatment with antivirals within 72 hours is ideal.",
    },
    # ── Orthopedics ──
    {
        "id": "ortho_001", "name": "Hip Fracture (Femoral Neck)", "icd10": "S72.0",
        "symptoms": "groin pain, inability to bear weight, shortened and externally rotated leg (displaced), groin tenderness, pain with passive rotation",
        "specialties": "Orthopedics, Geriatric Medicine",
        "prevalence": "very common in elderly", "risk_factors": "osteoporosis, falls, age >65, female sex, previous fracture, corticosteroid use, vitamin D deficiency",
        "demographics": "females > males, 80% are elderly (>65)",
        "red_flags": "avascular necrosis risk (intracapsular), nonunion, DVT/PE, surgical emergency in elderly",
        "urgency": "urgent",
        "description": "Fracture of the proximal femur. In elderly, usually from falls. Intracapsular fractures risk avascular necrosis. Requires surgical fixation within 24-48 hours.",
    },
    {
        "id": "ortho_002", "name": "Hip Fracture (Intertrochanteric)", "icd10": "S72.1",
        "symptoms": "groin/thigh pain, inability to bear weight, shortened and externally rotated leg, thigh swelling, pain with movement",
        "specialties": "Orthopedics",
        "prevalence": "very common in elderly", "risk_factors": "osteoporosis, falls, age >70, female sex, dementia (increased fall risk)",
        "demographics": "elderly, median age 80",
        "red_flags": "blood loss (can lose 1-2 units), DVT/PE, pressure ulcers, delirium, pneumonia (post-operative)",
        "urgency": "urgent",
        "description": "Extracapsular fracture of the proximal femur. Better blood supply than femoral neck fracture. Treated with dynamic hip screw or intramedullary nail.",
    },
    {
        "id": "ortho_003", "name": "Distal Radius Fracture (Colles')", "icd10": "S52.5",
        "symptoms": "wrist pain, swelling, deformity (dinner fork deformity), tenderness over distal radius, limited wrist motion, median nerve symptoms",
        "specialties": "Orthopedics, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "osteoporosis, falls on outstretched hand, elderly women, low trauma in elderly",
        "demographics": "bimodal: young adults (high energy) and elderly women >60 (low energy)",
        "red_flags": "median nerve compression (carpal tunnel), compartment syndrome, intra-articular involvement",
        "urgency": "urgent",
        "description": "Fracture of the distal radius with dorsal displacement (Colles'). Most common fracture in elderly women. Usually treated with casting, sometimes requires surgical fixation.",
    },
    {
        "id": "ortho_004", "name": "Rotator Cuff Tear", "icd10": "M75.1",
        "symptoms": "shoulder pain, weakness with abduction/external rotation, night pain, inability to lift arm, clicking, atrophy of supraspinatus/infraspinatus",
        "specialties": "Orthopedics, Sports Medicine",
        "prevalence": "very common", "risk_factors": "age >40, overhead sports/occupations, trauma, impingement, poor blood supply, smoking",
        "demographics": "adults >40, increases with age",
        "red_flags": "acute complete tear (inability to lift arm), massive tear, nerve injury",
        "urgency": "routine",
        "description": "Tear in one or more of the four rotator cuff tendons. Partial tears may heal; full-thickness tears often require surgical repair.",
    },
    # ── OB/GYN ──
    {
        "id": "obgyn_001", "name": "Ectopic Pregnancy", "icd10": "O00",
        "symptoms": "abdominal pain, missed period, vaginal bleeding, shoulder tip pain (diaphragmatic irritation), syncope, hypotension (ruptured), adnexal mass on ultrasound",
        "specialties": "Obstetrics/Gynecology, Emergency Medicine",
        "prevalence": "common", "risk_factors": "PID, tubal surgery, IUD use, prior ectopic, smoking, infertility treatment, endometriosis",
        "demographics": "reproductive-age females, 2-3% of pregnancies",
        "red_flags": "ruptured ectopic (hemodynamic instability, peritoneal signs), β-hCG not rising normally, adnexal mass",
        "urgency": "emergency",
        "description": "Implantation of embryo outside the uterine cavity, usually in the fallopian tube. Can be life-threatening if ruptured. Treatment: methotrexate or surgery.",
    },
    {
        "id": "obgyn_002", "name": "Ovarian Torsion", "icd10": "N83.2",
        "symptoms": "sudden severe lower abdominal pain, nausea, vomiting, adnexal mass, tenderness, fever, pelvic pain",
        "specialties": "Gynecology, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "ovarian cyst/mass >5 cm, ovarian hyperstimulation, pregnancy, prior torsion",
        "demographics": "reproductive-age women, peak 20-30",
        "red_flags": "ovarian necrosis (delayed treatment), peritonitis, sepsis",
        "urgency": "emergency",
        "description": "Rotation of the ovary on its ligamentous supports, compromising blood supply. Surgical emergency requiring detorsion to save the ovary.",
    },
    {
        "id": "obgyn_003", "name": "Pre-eclampsia/Eclampsia", "icd10": "O14-O15",
        "symptoms": "hypertension (>140/90), proteinuria, headache, visual disturbances (scotomata, flashing lights), epigastric pain, edema, hyperreflexia (eclampsia), seizures (eclampsia)",
        "specialties": "Obstetrics, Maternal-Fetal Medicine",
        "prevalence": "common (5-8% of pregnancies)", "risk_factors": "first pregnancy, multiple gestation, obesity, advanced maternal age, prior pre-eclampsia, chronic hypertension",
        "demographics": "pregnant women, typically after 20 weeks",
        "red_flags": "HELLP syndrome (hemolysis, elevated LFTs, low platelets), eclamptic seizures, placental abruption, stroke, pulmonary edema",
        "urgency": "emergency",
        "description": "Hypertensive disorder of pregnancy with end-organ damage. Eclampsia (seizures) is a life-threatening emergency. Definitive treatment is delivery.",
    },
    {
        "id": "obgyn_004", "name": "Placenta Previa", "icd10": "O44",
        "symptoms": "painless bright red vaginal bleeding in 2nd/3rd trimester, soft non-tender uterus, high presenting part, bleeding may be massive",
        "specialties": "Obstetrics, Maternal-Fetal Medicine",
        "prevalence": "moderate", "risk_factors": "prior placenta previa, prior cesarean section, multiparity, advanced maternal age, smoking, IVF",
        "demographics": "pregnant women, 2nd/3rd trimester",
        "red_flags": "massive hemorrhage, hemodynamic instability, preterm delivery, morbidly adherent placenta (accreta)",
        "urgency": "emergency",
        "description": "Placenta covering or near the cervical os causing painless vaginal bleeding. Management depends on gestational age and severity of bleeding.",
    },
    {
        "id": "obgyn_005", "name": "Placental Abruption", "icd10": "O45",
        "symptoms": "vaginal bleeding, painful rigid uterus, abdominal pain, tenderness, contractions, fetal distress, dark vaginal bleeding, maternal hypotension",
        "specialties": "Obstetrics, Maternal-Fetal Medicine",
        "prevalence": "moderate", "risk_factors": "hypertension, preeclampsia, trauma, smoking, cocaine use, prior abruption, multiple gestation",
        "demographics": "pregnant women, 3rd trimester",
        "red_flags": "Couvelaire uterus (intrauterine hemorrhage), DIC, fetal death, maternal hemorrhagic shock",
        "urgency": "emergency",
        "description": "Premature separation of placenta from uterine wall before delivery. Can cause severe maternal and fetal hemorrhage. Requires immediate delivery in severe cases.",
    },
    # ── Pediatrics ──
    {
        "id": "peds_001", "name": "Febrile Seizure (Simple)", "icd10": "R56.0",
        "symptoms": "generalized tonic-clonic seizure in child with fever, duration <15 minutes, no recurrence in 24 hours, normal neurological exam",
        "specialties": "Pediatrics, Emergency Medicine",
        "prevalence": "very common (2-5% of children)", "risk_factors": "age 6 months to 5 years, high fever, family history, viral infection, rapid temperature rise",
        "demographics": "children 6 months to 5 years, peak 12-18 months",
        "red_flags": "complex febrile seizure (focal, prolonged >15 min, recurrence), first seizure >5 years, post-ictal focal deficit",
        "urgency": "urgent",
        "description": "Seizures triggered by fever in young children without intracranial infection or defined cause. Usually benign. Complex seizures need further workup.",
    },
    {
        "id": "peds_002", "name": "Pyloric Stenosis", "icd10": "K31.1",
        "symptoms": "non-bilious projectile vomiting, olive-shaped mass in RUQ, dehydration, weight loss, metabolic alkalosis, hungry vomiting (feeds then vomits), visible peristalsis",
        "specialties": "Pediatrics, General Surgery",
        "prevalence": "common", "risk_factors": "male sex 4:1, first-born, family history, bottle feeding, macrolide antibiotics in first weeks of life",
        "demographics": "infants 2-8 weeks, peak 3-6 weeks",
        "red_flags": "severe dehydration, hypochloremic metabolic alkalosis, shock",
        "urgency": "urgent",
        "description": "Hypertrophy of the pyloric sphincter muscle causing gastric outlet obstruction. Treated with pyloromyotomy (Ramstedt procedure).",
    },
    {
        "id": "peds_003", "name": "Intussusception", "icd10": "K56.1",
        "symptoms": "episodic colicky abdominal pain (drawing up legs), vomiting, bloody stool (currant jelly stool), abdominal mass (RUQ), lethargy, red currant jelly stools",
        "specialties": "Pediatrics, General Surgery",
        "prevalence": "most common cause of bowel obstruction in infants", "risk_factors": "viral infection (adenovirus), Meckel diverticulum, lymphoma, polyps, age <2 years",
        "demographics": "infants 6-36 months, males 2:1",
        "red_flags": "bowel ischemia, perforation, peritonitis, shock",
        "urgency": "emergency",
        "description": "Telescoping of bowel segments, most commonly ileocolic. Most common in males 6-18 months. Treatment: air/contrast enema reduction, surgery if fails.",
    },
    {
        "id": "peds_004", "name": "Meningitis (Bacterial, Pediatric)", "icd10": "G00",
        "symptoms": "fever, irritability, lethargy, poor feeding, high-pitched cry, bulging fontanelle (infants), neck stiffness, seizures, petechial rash",
        "specialties": "Pediatrics, Infectious Disease, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "age <1 month (GBS, E. coli), age <5 (S. pneumoniae, N. meningitidis), daycare, complement deficiency, asplenia",
        "demographics": "neonates, infants, young children",
        "red_flags": "seizures, altered consciousness, septic shock, subdural empyema, hydrocephalus",
        "urgency": "emergency",
        "description": "Life-threatening infection of the meninges in children. Neonatal meningitis has different pathogens than older children. Empiric antibiotics must not be delayed.",
    },
    {
        "id": "peds_005", "name": "Croup (Laryngotracheobronchitis)", "icd10": "J04.2",
        "symptoms": "barking cough, stridor, hoarseness, inspiratory distress, low-grade fever, worse at night, seal-like cough",
        "specialties": "Pediatrics, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "age 6 months to 3 years, parainfluenza virus, fall/winter season, recurrent episodes",
        "demographics": "children 6 months to 3 years",
        "red_flags": "severe respiratory distress, cyanosis, silent chest, complete obstruction",
        "urgency": "urgent",
        "description": "Viral upper airway inflammation causing subglottic edema and the characteristic barking cough. Usually self-limiting. Dexamethasone and nebulized epinephrine for moderate-severe cases.",
    },
    {
        "id": "peds_006", "name": "Dehydration (Pediatric)", "icd10": "E86.0",
        "symptoms": "decreased urine output, dry mucous membranes, sunken eyes, reduced skin turgor, tachycardia, lethargy, crying without tears, no wet diapers",
        "specialties": "Pediatrics, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "viral gastroenteritis (rotavirus), vomiting, diarrhea, poor intake, fever, excessive sweating",
        "demographics": "infants and young children (highest risk), developing countries",
        "red_flags": "severe dehydration (>10%), shock, altered consciousness, electrolyte abnormalities",
        "urgency": "urgent",
        "description": "Fluid loss exceeding intake in children. Classified as mild (5%), moderate (5-10%), severe (>10%). Children dehydrate faster than adults.",
    },
    # ── General Surgery ──
    {
        "id": "surg_001", "name": "Hernia (Inguinal)", "icd10": "K40",
        "symptoms": "inguinal bulge, pain with straining, groin discomfort, reducible mass, cough impulse, groin swelling",
        "specialties": "General Surgery",
        "prevalence": "very common", "risk_factors": "male sex, chronic cough, heavy lifting, obesity, ascites, prior abdominal surgery, premature birth",
        "demographics": "males 25:1 over females, peak in infants (indirect) and elderly (direct)",
        "red_flags": "incarceration (irreducible), strangulation (pain, tenderness, erythema, bowel obstruction), ischemia",
        "urgency": "urgent (if complicated)",
        "description": "Protrusion of abdominal contents through a defect in the abdominal wall. Indirect (congenital) or direct (acquired). Repair is the definitive treatment.",
    },
    {
        "id": "surg_002", "name": "Gallstones (Asymptomatic)", "icd10": "K80.2",
        "symptoms": "often asymptomatic, postprandial bloating, mild RUQ discomfort, fatty food intolerance",
        "specialties": "General Surgery, Gastroenterology",
        "prevalence": "very common (10-15% of adults)", "risk_factors": "5 Fs: female, forty, fertile, fat, fair; rapid weight loss, diabetes, total parenteral nutrition",
        "demographics": "females 40-60, more common with age",
        "red_flags": "progression to symptomatic disease, gallstone pancreatitis, cholecystitis, cholangitis, gallbladder cancer (rare)",
        "urgency": "routine",
        "description": "Crystalline deposits in the gallbladder. Most are cholesterol stones. Asymptomatic stones generally do not require treatment unless >3cm or in certain high-risk populations.",
    },
    {
        "id": "surg_003", "name": "Bowel Perforation", "icd10": "K63.1",
        "symptoms": "sudden severe abdominal pain, rigid (board-like) abdomen, absent bowel sounds, peritonitis, fever, tachycardia, free air on imaging",
        "specialties": "General Surgery, Emergency Medicine",
        "prevalence": "uncommon", "risk_factors": "peptic ulcer perforation, diverticulitis, appendicitis, trauma, IBD, ischemic colitis, cancer, perforation from endoscopy",
        "demographics": "depends on cause",
        "red_flags": "peritonitis, sepsis, multi-organ failure, death if untreated",
        "urgency": "emergency",
        "description": "Rupture of the gastrointestinal tract allowing intraperitoneal contamination. Causes peritonitis and sepsis. Requires emergent surgical repair.",
    },
    # ── Psychiatry ──
    {
        "id": "psych_001", "name": "Major Depressive Disorder", "icd10": "F32-F33",
        "symptoms": "persistent sadness, loss of interest (anhedonia), weight changes, sleep disturbance (insomnia/hypersomnia), psychomotor agitation/retardation, fatigue, feelings of worthlessness, difficulty concentrating, suicidal ideation",
        "specialties": "Psychiatry, Primary Care",
        "prevalence": "very common (8% of adults annually)", "risk_factors": "family history, prior episodes, trauma, stressful life events, chronic illness, substance use, female sex",
        "demographics": "females 2:1, onset typically 20-30, any age",
        "red_flags": "suicidal ideation with plan, psychotic features, catatonia, severe functional impairment",
        "urgency": "urgent",
        "description": "Persistent depressed mood or anhedonia for >2 weeks with functional impairment. Leading cause of disability worldwide. Treatment: psychotherapy, antidepressants.",
    },
    {
        "id": "psych_002", "name": "Bipolar Disorder (Manic Episode)", "icd10": "F30",
        "symptoms": "elevated or irritable mood, decreased need for sleep, pressured speech, flight of ideas, grandiosity, increased goal-directed activity, risky behavior, distractibility",
        "specialties": "Psychiatry",
        "prevalence": "moderate (1%)", "risk_factors": "family history (strongest), stress, sleep deprivation, substance use, childhood trauma",
        "demographics": "onset 15-25, equal sex distribution",
        "red_flags": "psychosis, suicidal ideation, dangerous behavior, severe functional impairment, mixed features",
        "urgency": "urgent",
        "description": "Mood disorder with episodes of mania and depression. Mania = elevated/irritable mood + increased energy for ≥7 days. Treatment: mood stabilizers (lithium).",
    },
    {
        "id": "psych_003", "name": "Generalized Anxiety Disorder", "icd10": "F41.1",
        "symptoms": "excessive worry (>6 months), difficulty controlling worry, restlessness, fatigue, difficulty concentrating, irritability, muscle tension, sleep disturbance",
        "specialties": "Psychiatry, Primary Care",
        "prevalence": "very common (5.7%)", "risk_factors": "female sex, family history, childhood adversity, stressful life events, chronic illness",
        "demographics": "females 2:1, onset typically in childhood/adolescence",
        "red_flags": "suicidal ideation, substance abuse, severe functional impairment",
        "urgency": "routine",
        "description": "Persistent and excessive worry about multiple domains for ≥6 months. Most common anxiety disorder. Treatment: CBT, SSRIs/SNRIs.",
    },
    {
        "id": "psych_004", "name": "Schizophrenia", "icd10": "F20",
        "symptoms": "hallucinations (auditory most common), delusions, disorganized speech, disorganized/catatonic behavior, negative symptoms (flat affect, alogia, avolition), social withdrawal",
        "specialties": "Psychiatry",
        "prevalence": "moderate (1%)", "risk_factors": "family history, cannabis use in adolescence, urban environment, migration, obstetric complications, childhood trauma",
        "demographics": "males: onset 18-25; females: onset 25-35, equal prevalence",
        "red_flags": "command hallucinations, suicidal ideation, violence risk, catatonia, medication non-compliance leading to relapse",
        "urgency": "urgent",
        "description": "Chronic psychotic disorder characterized by positive symptoms (hallucinations, delusions) and negative symptoms (flat affect, avolition). Treatment: antipsychotics.",
    },
    # ── Ophthalmology ──
    {
        "id": "ophth_001", "name": "Acute Angle-Closure Glaucoma", "icd10": "H40.2",
        "symptoms": "sudden severe eye pain, headache, nausea, vomiting, blurred vision, halos around lights, red eye, fixed mid-dilated pupil, elevated intraocular pressure",
        "specialties": "Ophthalmology, Emergency Medicine",
        "prevalence": "uncommon", "risk_factors": "hyperopia, shallow anterior chamber, family history, age >40, pupillary dilation, Asian descent",
        "demographics": "adults over 40, females more, Asian descent",
        "red_flags": "permanent vision loss within hours, optic nerve damage, corneal edema",
        "urgency": "emergency",
        "description": "Rapid increase in intraocular pressure from closure of the drainage angle. An ophthalmic emergency requiring immediate treatment to prevent permanent blindness.",
    },
    {
        "id": "ophth_002", "name": "Retinal Detachment", "icd10": "H33",
        "symptoms": "sudden flashes of light, floaters, curtain/shadow over visual field, progressive vision loss",
        "specialties": "Ophthalmology",
        "prevalence": "moderate", "risk_factors": "myopia, prior cataract surgery, trauma, family history, lattice degeneration, PDR",
        "demographics": "adults 40-70, myopes, males > females",
        "red_flags": "macula-off detachment (worse prognosis), giant retinal tear",
        "urgency": "emergency",
        "description": "Separation of the neurosensory retina from the retinal pigment epithelium. Requires urgent surgical repair to preserve vision.",
    },
    # ── ENT ──
    {
        "id": "ent_001", "name": "Epistaxis (Severe Anterior)", "icd10": "R04.0",
        "symptoms": "bleeding from nostril (anterior septum), blood dripping, anxiety, mild hypotension if severe/prolonged",
        "specialties": "ENT, Emergency Medicine",
        "prevalence": "very common", "risk_factors": "digital trauma, dry air, nasal septum deviation, hypertension, anticoagulant use, hereditary hemorrhagic telangiectasia",
        "demographics": "bimodal: children 2-10 and adults 50-80",
        "red_flags": "posterior epistaxis (severe bleeding requiring packing/surgery), hemodynamic instability, coagulopathy",
        "urgency": "urgent",
        "description": "Bleeding from the nasal vessels. 90% are anterior (Kiesselbach plexus). Posterior bleeds are more severe and require ENT intervention.",
    },
    {
        "id": "ent_002", "name": "Peritonsillar Abscess", "icd10": "J36",
        "symptoms": "severe sore throat (unilateral), trismus, dysphagia, drooling, hot potato voice, fever, referred otalgia, uvular deviation",
        "specialties": "ENT, Emergency Medicine",
        "prevalence": "common", "risk_factors": "recurrent tonsillitis, young adults, smoking, poor dental hygiene",
        "demographics": "young adults 15-30",
        "red_flags": "airway compromise, extension to deep neck spaces (Ludwig angina, parapharyngeal abscess), aspiration",
        "urgency": "urgent",
        "description": "Collection of pus in the peritonsillar space, usually a complication of acute tonsillitis. Treatment: needle aspiration or incision and drainage + antibiotics.",
    },
    # ── Urology ──
    {
        "id": "urol_001", "name": "Benign Prostatic Hyperplasia", "icd10": "N40",
        "symptoms": "weak urine stream, hesitancy, frequency, urgency, nocturia, incomplete emptying, straining, overflow incontinence",
        "specialties": "Urology",
        "prevalence": "very common in elderly (50% at age 60, 90% at age 85)", "risk_factors": "age, male sex, family history, obesity",
        "demographics": "males over 50",
        "red_flags": "acute urinary retention, bladder stones, recurrent UTIs, renal insufficiency, post-renal failure",
        "urgency": "urgent (if urinary retention)",
        "description": "Non-cancerous enlargement of the prostate gland compressing the urethra. Most common cause of lower urinary tract symptoms in older men.",
    },
    {
        "id": "urol_002", "name": "Testicular Torsion", "icd10": "N44",
        "symptoms": "sudden severe scrotal pain, nausea, vomiting, swollen/tender testicle, high-riding testicle, loss of cremasteric reflex, horizontal lie of testis",
        "specialties": "Urology, Emergency Medicine",
        "prevalence": "moderate", "risk_factors": "adolescence, bell-clapper deformity, prior episodes, cold temperature, trauma",
        "demographics": "males 12-18 (peak), bimodal: neonates and adolescents",
        "red_flags": "testicular necrosis (>6 hours without detorsion), permanent infertility",
        "urgency": "emergency",
        "description": "Rotation of the testicle on its spermatic cord, cutting off blood supply. Surgical emergency — must be detorsed within 6 hours for best salvage rate.",
    },
]
