"""Respiratory system diagnoses (ICD-10 chapter X)."""

PULMONOLOGY_DIAGNOSES: list[dict] = [
    {
        "id": "pulm_001", "name": "Pneumonia (Community-Acquired)", "icd10": "J18",
        "symptoms": "fever, cough with sputum, shortness of breath, chest pain (pleuritic), chills, malaise, crackles on auscultation, decreased breath sounds",
        "specialties": "Pulmonology, Internal Medicine, Infectious Disease",
        "prevalence": "very common", "risk_factors": "smoking, COPD, immunosuppression, alcoholism, diabetes, heart failure, elderly, aspiration risk",
        "demographics": "all ages, higher mortality in elderly and very young",
        "red_flags": "respiratory failure, sepsis, multilobar involvement, empyema, parapneumonic effusion",
        "urgency": "urgent",
        "description": "Infection of lung parenchyma acquired outside the hospital. Most commonly bacterial (Streptococcus pneumoniae). Can range from mild to life-threatening.",
    },
    {
        "id": "pulm_002", "name": "Asthma (Acute Exacerbation)", "icd10": "J45.9",
        "symptoms": "wheezing, shortness of breath, chest tightness, cough (especially at night), difficulty speaking in full sentences, accessory muscle use, peak flow reduction",
        "specialties": "Pulmonology, Emergency Medicine, Allergy/Immunology",
        "prevalence": "very common", "risk_factors": "allergies, atopy, exercise, cold air, respiratory infections, air pollution, smoke exposure",
        "demographics": "all ages, more common in children, higher in urban populations",
        "red_flags": "silent chest (severe), inability to speak, SpO2 <90%, peak flow <50% predicted, exhaustion, cyanosis",
        "urgency": "emergency",
        "description": "Reversible airway obstruction with bronchospasm, inflammation, and mucus production. Ranges from mild intermittent to severe persistent.",
    },
    {
        "id": "pulm_003", "name": "COPD (Chronic Obstructive Pulmonary Disease)", "icd10": "J44",
        "symptoms": "chronic cough, sputum production, shortness of breath on exertion, wheezing, barrel chest, prolonged expiratory phase, pursed-lip breathing, fatigue",
        "specialties": "Pulmonology",
        "prevalence": "very common", "risk_factors": "smoking (primary), biomass fuel exposure, alpha-1 antitrypsin deficiency, occupational dust",
        "demographics": "adults over 40, males (though catching up in females), smokers",
        "red_flags": "acute exacerbation with increased dyspnea, change in sputum color/volume, respiratory failure, cor pulmonale",
        "urgency": "urgent",
        "description": "Progressive airflow limitation from chronic inflammation. Includes emphysema and chronic bronchitis. Third leading cause of death worldwide.",
    },
    {
        "id": "pulm_004", "name": "Pneumothorax (Spontaneous)", "icd10": "J93",
        "symptoms": "sudden chest pain, shortness of breath, decreased breath sounds on affected side, tachycardia, tachypnea, hyperresonance to percussion",
        "specialties": "Emergency Medicine, Pulmonology, Thoracic Surgery",
        "prevalence": "moderate", "risk_factors": "tall thin males, smoking, Marfan syndrome, Ehlers-Danlos, COPD, underlying lung disease",
        "demographics": "primary: males 20-40 tall/thin; secondary: elderly with lung disease",
        "red_flags": "tension pneumothorax (tracheal deviation, hypotension, JVD), large pneumothorax, bilateral",
        "urgency": "emergency",
        "description": "Air in the pleural space causing lung collapse. Tension pneumothorax is immediately life-threatening requiring needle decompression.",
    },
    {
        "id": "pulm_005", "name": "Pleural Effusion", "icd10": "J90",
        "symptoms": "shortness of breath (especially when lying flat), decreased breath sounds, dullness to percussion, pleuritic chest pain, cough, weight loss",
        "specialties": "Pulmonology, Internal Medicine",
        "prevalence": "common", "risk_factors": "heart failure, cancer, pneumonia, TB, cirrhosis, pulmonary embolism, autoimmune disease",
        "demographics": "depends on underlying cause",
        "red_flags": "large effusion with respiratory compromise, empyema (fever, sepsis), hemorrhagic effusion",
        "urgency": "urgent",
        "description": "Fluid accumulation in the pleural space. Can be transudative (heart failure, cirrhosis) or exudative (infection, malignancy, autoimmune).",
    },
    {
        "id": "pulm_006", "name": "Tuberculosis (Pulmonary)", "icd10": "A15",
        "symptoms": "chronic cough (>2 weeks), hemoptysis, night sweats, fever, weight loss, fatigue, chest pain, anorexia",
        "specialties": "Pulmonology, Infectious Disease",
        "prevalence": "common worldwide", "risk_factors": "endemic areas, HIV, immunosuppression, homelessness, incarceration, close contact, malnutrition",
        "demographics": "all ages, higher in developing countries, young adults",
        "red_flags": "hemoptysis, respiratory failure, miliary TB, meningitis, drug-resistant TB",
        "urgency": "urgent",
        "description": "Infection with Mycobacterium tuberculosis. Primarily affects lungs but can disseminate. Requires prolonged multi-drug therapy.",
    },
    {
        "id": "pulm_007", "name": "Lung Cancer (Non-Small Cell)", "icd10": "C34",
        "symptoms": "persistent cough, hemoptysis, weight loss, chest pain, shortness of breath, hoarseness, recurrent pneumonia, bone pain, headache",
        "specialties": "Oncology, Pulmonology, Thoracic Surgery",
        "prevalence": "common", "risk_factors": "smoking (85%), radon exposure, asbestos, air pollution, family history, prior radiation",
        "demographics": "adults over 55, males slightly more than females",
        "red_flags": "superior vena cava syndrome, Horner syndrome, Pancoast tumor, brain metastases, bone pain",
        "urgency": "urgent",
        "description": "Most common cancer worldwide. Includes adenocarcinoma, squamous cell, and large cell subtypes. Often diagnosed at advanced stage.",
    },
    {
        "id": "pulm_008", "name": "Pulmonary Hypertension", "icd10": "I27",
        "symptoms": "shortness of breath on exertion, fatigue, chest pain, syncope, peripheral edema, ascites, cyanosis, loud P2, jugular venous distension",
        "specialties": "Pulmonology, Cardiology",
        "prevalence": "uncommon", "risk_factors": "left heart disease, lung disease/hypoxia, chronic thromboembolic disease, connective tissue disease, congenital heart disease",
        "demographics": "females 2:1, ages 30-50 for idiopathic",
        "red_flags": "right heart failure, syncope, refractory edema, WHO functional class III-IV",
        "urgency": "urgent",
        "description": "Elevated pulmonary artery pressures causing right heart failure. Can be idiopathic or secondary to various conditions.",
    },
    {
        "id": "pulm_009", "name": "Pulmonary Fibrosis (Idiopathic)", "icd10": "J84.1",
        "symptoms": "progressive shortness of breath, dry cough, fatigue, weight loss, crackles on auscultation (velcro-like), digital clubbing, exercise intolerance",
        "specialties": "Pulmonology",
        "prevalence": "moderate", "risk_factors": "smoking, environmental exposures, medications (amiodarone, methotrexate), family history, autoimmune disease",
        "demographics": "males over 50, median age at diagnosis 65-70",
        "red_flags": "acute exacerbation with rapid decline, respiratory failure, pulmonary hypertension",
        "urgency": "urgent",
        "description": "Progressive scarring of lung tissue with unknown cause. Median survival 3-5 years from diagnosis. No cure without lung transplant.",
    },
    {
        "id": "pulm_010", "name": "Sarcoidosis (Pulmonary)", "icd10": "D86",
        "symptoms": "cough, shortness of breath, chest pain, fatigue, fever, weight loss, bilateral hilar lymphadenopathy, skin lesions (erythema nodosum), eye inflammation",
        "specialties": "Pulmonology, Rheumatology",
        "prevalence": "moderate", "risk_factors": "genetic predisposition, environmental triggers (infections, dust), African American, Scandinavian descent",
        "demographics": "females 20-40, African Americans higher prevalence and severity",
        "red_flags": "progressive pulmonary fibrosis, cardiac involvement, neurosarcoidosis, ocular involvement",
        "urgency": "urgent",
        "description": "Systemic granulomatous disease of unknown etiology. Most commonly affects lungs and intrathoracic lymph nodes. Can involve any organ.",
    },
    {
        "id": "pulm_011", "name": "Pulmonary Embolism", "icd10": "I26",
        "symptoms": "sudden shortness of breath, pleuritic chest pain, cough, hemoptysis, tachycardia, tachypnea, low oxygen saturation, syncope, leg swelling",
        "specialties": "Pulmonology, Emergency Medicine, Hematology",
        "prevalence": "common", "risk_factors": "immobility, surgery, cancer, oral contraceptives, pregnancy, obesity, DVT history, thrombophilia",
        "demographics": "adults 40-80, higher in females with risk factors",
        "red_flags": "massive PE with hypotension, cardiac arrest, right heart failure, syncope, respiratory failure",
        "urgency": "emergency",
        "description": "Blood clot in pulmonary vasculature, usually from deep vein thrombosis. Can range from subsegmental to massive with hemodynamic collapse.",
    },
    {
        "id": "pulm_012", "name": "Obstructive Sleep Apnea", "icd10": "G47.3",
        "symptoms": "loud snoring, witnessed apneas, excessive daytime sleepiness, morning headaches, difficulty concentrating, mood changes, nocturia, gasping during sleep",
        "specialties": "Pulmonology, Sleep Medicine, ENT",
        "prevalence": "very common", "risk_factors": "obesity (BMI>30), male sex, neck circumference >17 inches, family history, tonsillar hypertrophy, alcohol/sedatives",
        "demographics": "males 2:1, middle-aged adults, post-menopausal women",
        "red_flags": "severe OSA (AHI>30), hypoxemia, pulmonary hypertension, resistant hypertension, atrial fibrillation",
        "urgency": "routine",
        "description": "Repetitive upper airway collapse during sleep causing hypoxemia and sleep fragmentation. Strongly associated with cardiovascular disease.",
    },
    {
        "id": "pulm_013", "name": "Bronchiectasis", "icd10": "J47",
        "symptoms": "chronic productive cough, large volumes of sputum, recurrent respiratory infections, hemoptysis, shortness of breath, wheezing, crackles",
        "specialties": "Pulmonology",
        "prevalence": "moderate", "risk_factors": "prior severe infection (childhood), cystic fibrosis, primary ciliary dyskinesia, immunodeficiency, allergic bronchopulmonary aspergillosis",
        "demographics": "all ages, depends on underlying cause",
        "red_flags": "massive hemoptysis, respiratory failure, malnutrition",
        "urgency": "urgent",
        "description": "Permanent dilation of bronchi due to chronic inflammation and infection. Results in impaired mucus clearance and recurrent infections.",
    },
    {
        "id": "pulm_014", "name": "Pertussis (Whooping Cough)", "icd10": "A37",
        "symptoms": "paroxysmal cough, inspiratory whoop, post-tussive vomiting, cyanosis during coughing fits, apnea (in infants), lymphocytosis",
        "specialties": "Infectious Disease, Pulmonology, Pediatrics",
        "prevalence": "moderate (outbreaks)", "risk_factors": "unvaccinated or under-vaccinated, infants at highest risk",
        "demographics": "infants most severe, children and adults for spread",
        "red_flags": "apnea in infants, pneumonia, encephalopathy, rib fractures from coughing",
        "urgency": "urgent",
        "description": "Bacterial infection (Bordetella pertussis) causing severe paroxysmal cough. Most dangerous in infants. Vaccine preventable.",
    },
    {
        "id": "pulm_015", "name": "Cystic Fibrosis", "icd10": "E84",
        "symptoms": "chronic cough with thick sputum, wheezing, recurrent lung infections, failure to thrive (children), steatorrhea, nasal polyps, clubbing, pancreatic insufficiency",
        "specialties": "Pulmonology, Gastroenterology, Genetics",
        "prevalence": "uncommon", "risk_factors": "autosomal recessive (CFTR mutation), Northern European descent",
        "demographics": "children and young adults, median predicted survival now >50 years",
        "red_flags": "acute exacerbation, pneumothorax, massive hemoptysis, CF-related diabetes, respiratory failure",
        "urgency": "urgent",
        "description": "Genetic disorder causing thick, sticky mucus in lungs and digestive tract. Progressive lung damage is the major cause of morbidity and mortality.",
    },
]
